### ISSUE TITLE
Master node not reachable after reboot or change ip

### ISSUE THREAD

**Issue by yaoxiaotong** [elastic/azure-marketplace#101]
I recently went into these issue several times. It happened right after reboot or changing the private ip address(I think reboot is done after this automatically). 

Ping the node works, but the Elasticsearch service is not reachable, and ssh connection is refused. 

This happens only in master nodes, data nodes are fine. 

To reproduce this, I deployed a new cluster, without doing any change, just reboot all the master nodes multiple time. In my case, one master node is not reachable after the second round of reboot. 

A easier way to reproduce is change the private ip  from dynamic to static and change the ip to another available address in the subnet. This guarantee to reproduce the problem. 

Several details on my deployment:
- Master node size: Standard_D1
- 10 Data nodes are using Standard_DS3_V2 with 2 large default disk each
- Elasticseach version: 2.3.5
- External load balancer
- Install Azure plugin
- using existing virtual net and subnet

I contacted Azure support then they have't figure out the issue. Is it possible this is because of the deployment template?

**Comment by yaoxiaotong** [comment]
I did a walk around by deploy 3 more data nodes and change them to master node. 

Anyone see the same problem?

**Comment by gmarz** [comment]
Possibly related to #102

**Comment by russcam** [comment]
@yaoxiaotong I just merged in a PR that should address this. Would you be able to try this again using commit `7709b1d0eb7f9f547a94f7022b97467bfeba3649` and let me know if this is now fixed? [You can deploy using a specific commit with Powershell or Azure CLI.](https://github.com/elastic/azure-marketplace#targeting-a-specific-template-version)
