### ISSUE TITLE
Restart of Client node VM results in read-only datadisk.

### ISSUE THREAD

**Issue by psibernetic** [elastic/azure-marketplace#102]
We deployed the cluster using this template.

We did a restart of the Client node VM; after the restart the elasticsearch service fails to start.

Looking in the logs indicated that elasticsearch:elasticsearch did not have access to /datadisks/disk1.

Doing a ls -l shows:
`dr--r--r--  4 root          root          4096 Feb 17 23:04 disk1`

Tried to change permissions/ownership, and remount the drive to other points and same with rw,user,noatime with no change. 

We aren't by any means decent with *nix over here, but I wouldn't think a reboot would take a node down like this. Any help would be greatly appreciated.

**Comment by psibernetic** [comment]
`mount -v` shows:
```
/dev/sdb1 on /datadisks/disk1 type ext4 (rw,noatime,nodiratime,data=ordered)
/dev/sdb1 on /mnt type ext4 (rw,relatime,data=ordered)
```

/etc/fstab shows (obfustcated the UUID):

```
UUID="3c678085-xxxx-xxxx-xxxx-d6128211c156"     /datadisks/disk1        ext4    noatime,nodiratime,nodev,noexec,nosuid  1 2
/dev/disk/cloud/azure_resource-part1    /mnt    auto    defaults,nofail,comment=cloudconfig     0       2
```

Making a change in `fstab` to rw,dev,suid,exec made no difference either.

**Comment by gmarz** [comment]
Thanks for the detailed info @psibernetic.  I'm looking into this.

**Comment by psibernetic** [comment]
Here is more info from our investigations:

We did a little more recon on this problem and found a number of issues:

 

1.      The client nodes didn't survive a reboot because of a permissioning problem in the primary mount point that holds the ES data directory /datadisks/disk1.  The client node VMs were configured by the azure marketplace template to have no additional data disks attached.  The custom VM configuration script "/src/scripts/vm-disk-utils-0.1.sh" then created an additional mount point against the temporary disk and placed the data directory there.  For some reason a reboot seems to have lowered the permission level of that mount.  We think this can be fixed by editing the fstab entry to change ownership of the mount to the "elasticsearch" user.  But we're concerned that we may not want to place the ES data folder on the temporary disk.  We need to confirm whether this should go onto the temporary disk or onto the permanent disk holding the root partition.  This would affect any VMs that did not have additional data disks attached (so master and client nodes).

2.      The data nodes have multiple problems:

o   The azure marketplace script output shows that the correct data disks were detected and partitioned. It seems to show that they were then striped via mdadm correctly.  However mdadm is now showing that only one of the two available partitions (/dev/sdd1) was placed into the RAID array.

o   The azure marketplace script output shows that no fstab entry was created for the RAID array md0 since the UUID seems to have been found in the fstab at the time the script ran.  Currently, there is no entry for the RAID array in /etc/fstab and there is no reason to suspect that a prior entry was there when vm-disk-utils-0.1.sh ran.  Also, because of a lack of fstab entry, the data nodes would not survive reboot (*caveat that they actually would in the current case because of the next bug)

o   The RAID array md0 was never mounted correctly the first time (despite the script attempting to mount it to /datadisks/disk1).  This problem went undetected by the azure marketplace script and it continued to write the ES data directory to the root partition.  The end result is that the 1TB of additional attached ssds are being completely ignored by the cluster and all data is being written to a small drive where the root is mounted.

**Comment by gmarz** [comment]
@psibernetic thanks for digging in and providing the additional info, very helpful!

Few questions to help me reproduce this.  I'm assuming you're deploying from the ARM template itself and not through the Marketplace?  If so:

 - Are you deploying from a specific release or master?  If so, what version?
 - Can you provide your parameters.json file here?  (with any sensitive data removed!)

**Comment by psibernetic** [comment]
We forked and ran from master. Deployed using the template.

parameters
```json
{
	"artifactsBaseUrl":{"value":"https://raw.githubusercontent.com/elastic/azure-marketplace/master/src"},
	"esVersion":{"value":"5.1.2"},
	"esClusterName":{"value":"elasticsearch"},
	"location":{"value":"westus"},
	"esPlugins":{"value":"Yes"},
	"esAdditionalPlugins": { "value": " " },
	"azureCloudPlugin":{"value":"No"},
	"azureCloudStorageAccountName":{"value":""},
	"azureCloudStorageAccountKey":{"value":""},
	"loadBalancerType":{"value":"internal"},
	"kibana":{"value":"Yes"},
	"jumpbox":{"value":"Yes"},
	"vmHostNamePrefix":{"value":"**-"},
	"vmSizeKibana":{"value":"Standard_A1"},
	"vmDataDiskSize":{"value":"Medium"},
	"vmSizeDataNodes":{"value":"Standard_DS4_v2"},
	"vmDataNodeCount":{"value":4},
	"dataNodesAreMasterEligible":{"value":"No"},
	"vmSizeMasterNodes":{"value":"Standard_A3"},
	"vmClientNodeCount":{"value":2},
	"vmSizeClientNodes":{"value":"Standard_DS4_v2"},
	"adminUsername":{"value":"admin"},
	"authenticationType":{"value":"sshPublicKey"},
	"sshPublicKey":{"value":"{KEYHERE}"},
	"adminPassword":{"value":""},
	"securityAdminPassword":{"value":"*************"},
	"securityReadPassword":{"value":"***************"},
	"securityKibanaPassword":{"value":"**************"},
	"vNetName": {"value": "es-net"},
	"vNetSubnetName": {"value": "es-subnet"},
	"vNetLoadBalancerIp": {"value": "10.0.0.4"},
    "vNetNewOrExisting": {"value":"new"},
    "vNetExistingResourceGroup": {"value": ""},
    "vNetNewAddressPrefix": {"value": "10.0.0.0/16"},   
    "vNetNewSubnetAddressPrefix": {"value": "10.0.0.0/24"},
	"userCompany": { "value": "" },
	"userEmail": { "value": "" },
	"userFirstName": { "value": "" },	
	"userLastName": { "value": "" },
	"userJobTitle": { "value": "Software Developer / Engineer"},
	"userCountry": { "value": "United States" }	
}
```

**Comment by psibernetic** [comment]
Additionally, we cahnged our disk set form 16 to 2 in the main file.

```json
      "Standard_DS4_v2": {
        "dataDisks": 2,
        "storageAccountType": "Premium_LRS"
      },
```

**Comment by silijon** [comment]
FYI, we were able to fix the deployed cluster with the following steps:

**CLIENT/MASTER NODES** (really any nodes without attached disk storage)
1. Remove the temp drive mount from /etc/fstab that the script added.
2. Move and re-point the data directory to the primary VM drive (mounted at /).

**DATA NODES**
1. Re-build the data node RAID array to contain the correct list of attached drives:

-- remove
mdadm --stop /dev/md0
mdadm --remove /dev/md0
mdadm --zero-superblock /dev/sda1 /dev/sdb1 ...

then followed the commands with same params from the bash script to:

-- re-create with the correct device list
mdadm --create (yada yada yada)
-- create fs
mkfs.ext4  (yada yada yada)

added the new md0 device back to /etc/fstab (by uuid, also just copying from script)

-- update initramfs to ensure device is created as /dev/md0 (instead of /dev/md127)
update-initramfs -u

reboot just for laughs.

2. Move and re-point the data directory to the new mount (should be at /datadisks/disk1 if the script params were followed for fstab entry).


Can verify that everything works fine after that.  All other resources deployed from the ARM template and all the ES-specific settings look okay.

**Comment by russcam** [comment]
@psibernetic @silijon, I just merged in a PR into `master` that should address this. 

Would you be able to try this again using commit `7709b1d0eb7f9f547a94f7022b97467bfeba3649` and let me know if you experience any issues? [You can deploy using a specific commit with Powershell or Azure CLI.](https://github.com/elastic/azure-marketplace#targeting-a-specific-template-version)

**Comment by russcam** [comment]
@psibernetic @silijon 

I've dug into this further and merged in #119 with a fix that fixes this; I've run about 25 deployments and not seen the issues again.

Essentially,  _sometimes_ mdadm silently fails when creating RAID array on Ubuntu 16.04. Failure is not reflected in `mdadm --create` exit code but can be observed in /var/log/syslog, for example:

```sh
Apr 24 05:56:54 ubuntu kernel: [  135.370339]  sdd: sdd1
Apr 24 05:56:54 ubuntu kernel: [  135.376537]  sdd: sdd1
Apr 24 05:56:54 ubuntu kernel: [  135.482321] md: bind<sdc1>
Apr 24 05:56:54 ubuntu kernel: [  135.488211] md: bind<sdd1>
Apr 24 05:56:54 ubuntu kernel: [  135.489063] md/raid0:md0: md_size is 4290244608 sectors.
Apr 24 05:56:54 ubuntu kernel: [  135.489066] md: RAID0 configuration for md0 - 1 zone
Apr 24 05:56:54 ubuntu kernel: [  135.489067] md: zone0=[sdc1/sdd1]
Apr 24 05:56:54 ubuntu kernel: [  135.489071]       zone-offset=         0KB, device-offset=         0KB, size=2145122304KB
Apr 24 05:56:54 ubuntu kernel: [  135.489072]
Apr 24 05:56:54 ubuntu kernel: [  135.489143] md0: detected capacity change from 0 to 2196605239296
Apr 24 05:56:54 ubuntu systemd-udevd[9616]: Process '/sbin/mdadm --incremental /dev/sdd1 --offroot' failed with exit code 1.
Apr 24 05:56:54 ubuntu kernel: [  135.538883] md: md0 still in use.
Apr 24 05:56:54 ubuntu kernel: [  135.740580] md0: detected capacity change from 2196605239296 to 0
Apr 24 05:56:54 ubuntu kernel: [  135.740685] md: md0 stopped.
Apr 24 05:56:54 ubuntu kernel: [  135.740688] md: unbind<sdd1>
Apr 24 05:56:54 ubuntu kernel: [  135.740691] md: export_rdev(sdd1)
Apr 24 05:56:54 ubuntu kernel: [  135.740723] md: unbind<sdc1>
Apr 24 05:56:54 ubuntu kernel: [  135.740726] md: export_rdev(sdc1)
Apr 24 05:56:55 ubuntu kernel: [  135.882668] md: bind<sdd1>
```

The subsequent call to get the UUID from the created RAID0 datadisks returns an empty string which, when it attempts to add a record to `/etc/fstab`, it believes it's already there. Consequently, the mount for Elasticsearch becomes the OS disk `/ (/dev/sda1)`

There is a bug in mdadm that ships with Ubuntu 16.04: https://bugs.launchpad.net/ubuntu/+source/mdadm/+bug/1568097. Updating mdadm to latest available version _still_ exhibits the same intermittent failures.

The merged PR does several things to improve resiliency

1. check the exit code from `vm-disk-utils-0.1.sh` and fail the deployment if non-zero.
2. if retrieving the UUID returns empty, check the state of the RAID array; if inactive, stop it and assemble.
3. Check the state of the RAID array again. If active, all good, it not then bail with exit code 4.
4. If successful, then add entry to /etc/mdadm/mdadm.conf and update-initramfs

I'll keep this issue open for a little while longer, to garner feedback. If you'd like to try this out, target the `5.1.2` tag

**Comment by psibernetic** [comment]
@russcam Thanks for the work on this! We have already stood up our cluster and are in the middle of a large effort. As such, we don't have any resources on our team to dedicate towards this, so we will just go with your testing effort. That is a ton of deployments anyway haha.

**Comment by russcam** [comment]
Thanks for your detailed description on this issue @psibernetic and @silijon, it made it much easier to track down what might be happening 👍
