### ISSUE TITLE
Support the new L vm series

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/azure-marketplace#107]

**Comment by niemyjski** [comment]
What is all required for this? We are looking to setup a new cluster on L series

**Comment by russcam** [comment]
Looking to add these now

**Comment by shaharmor** [comment]
Any update on this?

**Comment by russcam** [comment]
@shaharmor most of the work has been done in the [feature/l-series](https://github.com/elastic/azure-marketplace/tree/feature/l-series) branch. The way in which the number of nodes per storage account needs to changed to accommodate the Standard_L32s sku that can have up to 64 disks attached per VM. 

Right now, the implementation assumes the maximum for any sku is 40, using this as the basis for determining how many storage accounts are required for the nodes. A lot of this template complexity is alleviated by using managed disks, which also allows encryption at rest, something that cannot be achieved currently with the Azure Disk Encryption implementation limitations. The desire is to use managed disks for potentially all attached disks but we need to investigate this further.

**Comment by okke-formsma** [comment]
Why not release this with a limitation on the number of disks, so we can at least use this deployment with a lower number of disks?

**Comment by okke-formsma** [comment]
Is there any progress on this? The L-series are very useful for deploying elastic on and have been available for more than a year now. Even without allowing 64 disks, support would be helpful. (Support for 64 disks could be added later?)
