### ISSUE TITLE
Data node creation failed (VMExtensionProvisioningError with status 10)

### ISSUE THREAD

**Issue by orient-man** [elastic/azure-marketplace#110]
Operation details:

    {
      "status": "Failed",
      "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
          {
            "code": "VMExtensionProvisioningError",
            "message": "VM has reported a failure when processing extension 'script'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=10\"."
          }
        ]
      }
    }

I logged into machine and found actual error during elasticsearch startup:

    ; line: 4, column: 33]]; nested: ParserException[while parsing a block node
     in 'reader', line 4, column 35:
        discovery.zen.ping.unicast.hosts: ]

Then I looked into code:

https://github.com/elastic/azure-marketplace/blame/master/src/scripts/elasticsearch-ubuntu-install.sh#L192

Maybe I'm missing something, but what "%?" part in

    UNICAST_HOSTS="${UNICAST_HOSTS%?}]"

suppose to do? Looks like a bug for me :)

**Comment by orient-man** [comment]
Mentioned line of code was executed because I encountered another problem (#111) which caused script parameters to be ignored. But it still looks wrong to me.

**Comment by russcam** [comment]
Hey @orient-man, 

`%?` is a [Parameter Substitution](http://www.tldp.org/LDP/abs/html/parameter-substitution.html) which effectively removes the trailing comma when building up the collection of unicast hosts from data nodes when not using dedicated master nodes:

```sh
    MINIMUM_MASTER_NODES=$(((DATANODE_COUNT/2)+1))
    UNICAST_HOSTS='['
    for i in $(seq 0 $((DATANODE_COUNT-1))); do
        UNICAST_HOSTS="$UNICAST_HOSTS\"${NAMESPACE_PREFIX}data-$i:9300\"," # <- remove this last trailing comma
    done
    UNICAST_HOSTS="${UNICAST_HOSTS%?}]"
```

Closing this; I've answered #111

**Comment by orient-man** [comment]
Thx, I learned something new today :). It works except the corner case when DATANODE_COUNT=0, then UNICAST_HOSTS='[' and %? just removes opening bracket. But DATANODE_COUNT=0 makes no sense and the real reason for that is #111. Thx again.

**Comment by russcam** [comment]
[DATANODE_COUNT in the context of the template can never be less than 1](https://github.com/elastic/azure-marketplace/blob/master/src/mainTemplate.json#L278-L285) 😄
