### ISSUE TITLE
Passwords with spaces break provisioning 

### ISSUE THREAD

**Issue by orient-man** [elastic/azure-marketplace#111]
After filling form generated template looks like this:

    "commandToExecute": "bash data-node-install.sh -zdln elk -v 5.1.2 -A your password with spaces and other parameters..."

Password is not inside quotes!

**Comment by russcam** [comment]
Hi @orient-man, this has been fixed in `master` in 78ed10d63b2f5fe040015c6feb954f39e8c3698f. 

Whats branch/commit are you deploying from?

**Comment by orient-man** [comment]
I used template from Azure Marketplace

**Comment by russcam** [comment]
We'll be updating the Azure Marketplace template soon; in the meantime, [you can deploy the template from github which includes the fix](https://github.com/elastic/azure-marketplace#command-line-deploy).

I'm going to close this issue.
