### ISSUE TITLE
Ubuntu Java Install failing for download.oracle.com not available

### ISSUE THREAD

**Issue by fifflr** [elastic/azure-marketplace#126]
Deployment script that is getting error ed out at JAVA Install step: https://github.com/elastic/azure-marketplace/blob/faf31d7a29377bd33693af7a72072c6c61442dcc/src/scripts/elasticsearch-ubuntu-install.sh

[09062017-00:07:37] [install_java] Seeing if java is Installed after nuclear retry 30/30
[09062017-00:07:37] Java did not get installed properly even after a retry and a forced installation
[09062017-00:07:37] installing Elasticsearch returned exit code 50

$ sudo add-apt-repository -y ppa:webupd8team/java
gpg: keyring `/tmp/tmpna0uwfbi/secring.gpg' created
gpg: keyring `/tmp/tmpna0uwfbi/pubring.gpg' created
gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpna0uwfbi/trustdb.gpg: trustdb created
gpg: key EEA14886: public key "Launchpad VLC" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
 sudo apt-get -yq install oracle-java8-installer
Reading package lists...
Building dependency tree...
Reading state information...
oracle-java8-installer is already the newest version (8u131-1~webupd8~2).
The following packages were automatically installed and are no longer required:
  libfontenc1 libxfont1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 170 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up libfontenc1:amd64 (1:1.1.3-1) ...
Setting up libxfont1:amd64 (1:1.5.1-1) ...
Setting up oracle-java8-installer (8u131-1~webupd8~2) ...
Using wget settings from /var/cache/oracle-jdk8-installer/wgetrc
Downloading Oracle Java 8...
--2017-06-09 01:00:54--  http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 23.61.194.27, 23.61.194.10
Connecting to download.oracle.com (download.oracle.com)|23.61.194.27|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz [following]
--2017-06-09 01:00:54--  https://edelivery.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.205.36.235, 2600:1406:2c:187::2d3e, 2600:1406:2c:191::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.205.36.235|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz?AuthParam=1496970174_348afa2702631e10f3100d446c9bf538 [following]
--2017-06-09 01:00:54--  http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz?AuthParam=1496970174_348afa2702631e10f3100d446c9bf538
Connecting to download.oracle.com (download.oracle.com)|23.61.194.27|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2017-06-09 01:00:54 ERROR 503: Service Unavailable.

download failed
Oracle JDK 8 is NOT installed.
dpkg: error processing package oracle-java8-installer (--configure):
subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.23-0ubuntu4) ...
Errors were encountered while processing:
oracle-java8-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by russcam** [comment]
Sadly, there is little we can do within a VM Script extension when a package required for deployment is unable to be downloaded; we do attempt to [retry downloading packages](https://github.com/elastic/azure-marketplace/blob/master/src/scripts/elasticsearch-ubuntu-install.sh#L270-L304) as a best effort.

@fifflr Have you tried re-running the deployment?

**Comment by fifflr** [comment]
Turns out the download was choking on the internal network team customizing Azure to block ports. Worked with internal network team to redo the firewall changes and deployment went thru. Thank you

**Comment by russcam** [comment]
Thanks for reporting back @fifflr. Glad you got the issue resolved 👍
