### ISSUE TITLE
Support RHEL RED HAT Linux

### ISSUE THREAD

**Issue by fifflr** [elastic/azure-marketplace#128]
Internal security team prefers RHEL. Is there some work being put against this effort.

**Comment by russcam** [comment]
Hey @fifflr,
 
There's nothing on the roadmap for RHEL; [Windows support](https://github.com/elastic/azure-marketplace/issues/12) is on the backlog but it's a low priority right now.

The template has been architected to support other distributions in the future, with most if not all OS specific settings encapsulated in one linked template e.g. [here's the one for Ubuntu](https://github.com/elastic/azure-marketplace/blob/master/src/settings/ubuntuSettings.json).

**Comment by russcam** [comment]
I'm going to close this issue for now, as there is currently no plan to implement this. If someone would like to tackle it and submit a PR, please reopen to discuss.
