### ISSUE TITLE
Logstash Integration

### ISSUE THREAD

**Issue by zchef2k** [elastic/azure-marketplace#129]
I'm interested in adding Logstash into the mix but am having a hard time with the x-pack piece of this deployment. Neither the logstash_system user nor indexes where created. Do you have any insight into how this would be achieved using this method?

**Comment by russcam** [comment]
Hey @zchef2k, how are you integrating it?  Do you have a link to a fork repository?

**Comment by zchef2k** [comment]
This can be ignored. After upgrading elasticsearch and kibana and reinstalling x-pack plugins on all 3 components, monitoring for Logstash appeared. This is more of an issue of versionitis in my deployment than anything.

Nothing to see here, I suppose. Closing.

**Comment by russcam** [comment]
Glad you got it sorted @zchef2k 👍

**Comment by zimmertr** [comment]
For anyone else coming here in the future... this will install Logstash:

```
#!/bin/bash
sudo ufw disable
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo apt-get install oracle-java9-installer -y < "/dev/null"
sudo chmod 777 /etc/environment
echo "PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin/java"" > /etc/environment
echo "JAVA_HOME="/usr/lib/jvm/java-9-oracle/"" >> /etc/environment
sudo chmod 644 /etc/environment
source /etc/environment
sudo su -c "source /etc/environment" root
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
sudo apt-get update
sudo apt-get install logstash apt-transport-https -y < "/dev/null"
sudo systemctl daemon-reload
sudo systemctl enable logstash
sudo systemctl start logstash
exit 0
```

**Comment by zimmertr** [comment]
I foolishly thought Logstash was part of this template when deploying...
