### ISSUE TITLE
How to connect to deployed template

### ISSUE THREAD

**Issue by MartinBodocky** [elastic/azure-marketplace#139]
Hi guys, 
I have deployed this template on my Azure. I have found that Kibana is working on port 5601.
The issue is I cannot find how to I can connect to elasticsearch to provision any data(like 9200 port when I install eleasticsearch locally).  I found there is open port 22 with SSH but I don't know how to use it.

Can I found any documentation about that?

The purpose is to replicate this solution: http://www.mpustelak.com/2016/12/log-data-using-serilog-elasticsearch-kibana/

When I use dev tools in Kibana for search it uses just internal IP:  "http://10.0.0.4:9200/_search" 

Thank you in advance,

Martin

**Comment by russcam** [comment]
Hi @MartinBodocky,

the template provides the option to configure external access to the Elasticsearch cluster through the [`loadBalancerType` parameter](https://github.com/elastic/azure-marketplace#parameters). By default, the load balancer deployed is internal meaning that no external access to the cluster is configured; Kibana has access to the cluster through the internal load balancer.

With the `loadBalancerType` parameter

- By providing a value of `external`, both internal and external load balancers will be deployed and you will be able to connect to the cluster through the external load balancer public IP address.

- By providing a value of `gateway`, Application Gateway will be deployed for load balancing, allowing a PFX certificate to be supplied for transport layer security (recommended for production) to and from Application Gateway, and providing SSL offload. You will be able to connect to the cluster through the Application Gateway public IP address.

I hope that helps 👍

**Comment by russcam** [comment]
Closing this as details provided for how to setup with external access.
