### ISSUE TITLE
Azure deployment - plugin:elasticsearch - Request Timeout after 1500ms  

### ISSUE THREAD

**Issue by MedAnd** [elastic/azure-marketplace#14]
Using the new Azure Market place template mentioned in this post: https://www.elastic.co/blog/microsoft-azure-marketplace-elasticsearch-kibana-and-more-now-available I deployed an Elastic cluster but get the below error:

plugin:elasticsearch - Request Timeout after 1500ms  
plugin:marvel - Waiting for Elasticsearch

**Comment by russcam** [comment]
Hey @MedAnd, @markwalkom forwarded on your email related to this too. Would you be able to indicate:

1. what cluster configuration you installed e.g. number of data nodes, ES version
2. if you're using an internal/external load balancer
3. if you set up a jump box
4. how you successful created indexes on the cluster.

Have you always seen both of those statuses, or were they initially green? How long have you had the cluster spun up for?

**Comment by MedAnd** [comment]
Hi @russcam 

Thank you for the follow-up.

1. After deploying, in Azure I can see the following Resources (the version was 2.01):

elasticsearchMaster
esdata-set
esdatavm0
esdatavm1
esdatavm2
kibana-vm
masterVm0
masterVm1
masterVm2

2. I believe the load balancer is external:

Protocol/port
TCP/9200, TCP/9300

Backend pool
LBBE (3 virtual machines)

Probe
esProbe (TCP:9200)

NAT rules
0 inbound 

3. I believe there is no jumpbox. I'm also connecting to Kibana directly on kibana-nsg TCP/5601.

4. I connected directly to ES on loadBalancer IP port 9200 and issued commands via Chrome Postman plugin to create indexes.

I've always seen the same failures. The cluster has been running for a couple of days. I hope the above helps, I could also privately send you the logon details?

**Comment by pickypg** [comment]
@MedAnd The easiest way to avoid this is to change the load balancer to `internal` during generation.

However, you can change the IP address within the `/opt/kibana/config/kibana.yml` to the public IP for the load balancer. Via the template, it cannot guess the public IP so it can't fill it in for you.

**Comment by MedAnd** [comment]
@pickypg As we are working with two Azure ARM deployed clusters (one of them being Elastic) I've opted for the external load balancer. I had to change the yml file as mentioned above. All working now, thank you for the assistance.

PS. Wondering if deployment to an existing Azure vNet will be supported in future versions of the Elastic ARM template?

**Comment by russcam** [comment]
@MedAnd I would recommend opening a new issue for deploying a cluster to an existing vNet so it doesn't get lost in the comments here :smile:

**Comment by Mpdreamz** [comment]
This has been fixed, see https://github.com/elastic/azure-marketplace/issues/18#issuecomment-183303402 for the details.

**Comment by frode** [comment]
@pickypg which user should be able to login and change the /opt/kibana/config/kibana.yml file?
I've only been able to ssh into the kibana server with es_admin, and it does not have the rights to make changes to the file ..

**Comment by Mpdreamz** [comment]
You will need to ssh into the box using the username/pass|key provided here:

![image](https://cloud.githubusercontent.com/assets/245275/15927958/aa9e5c1e-2e44-11e6-91e1-496f942aa48f.png)

Hoping to get a new release pushed to the production marketplace within the next weeks.

**Comment by frode** [comment]
Thanks, I got another reply from Martijn on email, I was only missing "sudo" to get the correct permission level to save! 👍
