### ISSUE TITLE
How to install license after the 30 day trial expires?

### ISSUE THREAD

**Issue by lmemmott** [elastic/azure-marketplace#141]
As describe on the project's web page here on github, it sets up resources in Azure with a 30-day trial for the x-pack plug-ins.  What is the process of installing a permanent license?  Would I have to SSH to each node in my cluster to install the license?  Can it be done through the Elasticsearch API?  

I just found this... Would this be right for Azure too?
https://www.elastic.co/guide/en/x-pack/current/installing-license.html

Thanks for your time!

**Comment by russcam** [comment]
Hey @lmemmott, you can use the license API to update the license for a cluster deployed on Azure with the ARM template as per the linked article. 

You can use [Kibana Console](https://www.elastic.co/guide/en/kibana/current/console-kibana.html) if you have also deployed Kibana.

**Comment by lmemmott** [comment]
Thanks so much!  I appreciate it.
