### ISSUE TITLE
Customize elasticsearch.yml through the ARM Templates?

### ISSUE THREAD

**Issue by lmemmott** [elastic/azure-marketplace#142]
If there are customizations that done through elasticsearch.yml to the runtime, is there a way to do that through the ARM templates?  Or would I need to SSH to each node and apply them?

Thanks for your time!

**Comment by russcam** [comment]
Hey @lmemmott, you can apply changes to `elasticsearch.yaml` file at deployment time with the [`esAdditionalYaml` parameter](https://github.com/elastic/azure-marketplace#parameters).

As per the note, this is an expert level feature - It is recommended that you run your additional yaml through a linter before starting a deployment to ensure it's valid.

**Comment by lmemmott** [comment]
Thanks so much!  I appreciate it.
