### ISSUE TITLE
No Public IP Addresses for location ‘westeurope’ and API version ‘2017-09-01’ 

### ISSUE THREAD

**Issue by russcam** [elastic/azure-marketplace#143]
[As reported on discuss](https://discuss.elastic.co/t/es-on-azure-version/98645/7)

**Comment by deepakvelani** [comment]
Hi Russcam,

I came across this same issue when i was deploying the environment today. I had deployed this environment inAapril and saved the arm script which i then used to deploy in another environment a few weeks later. Now i am using the same script to deploy it but get this same error.

I can send you the artifacts link it is using from Azure gallery if that helps?

**Comment by russcam** [comment]
Hey @deepakvelani,

I am working on an update to address this issue now

**Comment by deepakvelani** [comment]
Thanks Russ. 

Last night after i sent the message i tried again and it had worked. I have tried deploying again from the saved scripts and that has worked as well.

**Comment by russcam** [comment]
Good to hear it worked the next time @deepakvelani.

To clarify, I received confirmation from Microsoft that this was related to new API versions rolled out in some regions but not all, so the issue is likely to have been intermittent. #144 addresses this issue from happening in the future.

**Comment by deepakvelani** [comment]
Thanks for the update Russ
