### ISSUE TITLE
Update versions

### ISSUE THREAD

**Issue by skuda** [elastic/azure-marketplace#147]
Elastic 5.5.2, 5.5.3, 5.6.0, 5.6.1 are versions already released.

I just tried this template and it works very well, well done, but I think the version used is a bit old already. I am interested in using at least 5.6.0 because we want to migrate some old indexes we have around to an Azure cluster and the deprecation warnings would be useful.

Best,
Miguel.

**Comment by russcam** [comment]
@skuda We'll be releasing a version to the Azure Marketplace shortly with support for 5.6.2.

If you're running from the command line, you can target this version already by using the [5.6.2 tagged release](https://github.com/elastic/azure-marketplace/tree/5.6.2).

Hope that helps 👍
