### ISSUE TITLE
Support deployment to an existing Azure vNet in future versions of the Elastic ARM template

### ISSUE THREAD

**Issue by MedAnd** [elastic/azure-marketplace#15]
I attempted deploying to an existing Azure Resource Group which is already running another Cluster of .Net compute nodes (Service Fabric) but the deployment failed. If possible it would be great to support deploying an ES cluster to an existing Azure vNet.

**Comment by Mpdreamz** [comment]
++ this is high on our backlog

**Comment by MedAnd** [comment]
@Mpdreamz - Let me know if you need any guinea pigs :+1:

**Comment by elmalto** [comment]
any updates on this?

**Comment by ajhewett** [comment]
#37 is a possible solution.

**Comment by russcam** [comment]
@ajhewett I'm working on updating this in line with new changes to the template

**Comment by russcam** [comment]
This will be in the next template release, once it's gone through the approval process.
