### ISSUE TITLE
With the release of Elasticsearch 6.0 today, when will the ARM templates support it?

### ISSUE THREAD

**Issue by lmemmott** [elastic/azure-marketplace#151]
Today is an exciting day with the release of Elasticsearch 6.0.  Can you tell us when you think the ARM templates will support it?

Thanks in advance.

**Comment by Mpdreamz** [comment]
The `.NET client` currently takes priority from our team which will take another week. 

After that we have the bandwidth to get 6.0 support baked in to the ARM template. It will take an estimated week to make sure we cover all the [`x-pack` breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-6.0.0-xes.html).

Note: rough estimates only, trying to be open about the roadmap without committing to a hard date.

**Comment by adlangx** [comment]
Any word on when this might happen?

**Comment by ravitejag** [comment]
Any update? Thanks.

**Comment by jessebenson** [comment]
Is this still being planned?

**Comment by russcam** [comment]
@ravitejag @jessebenson yes, this is still being planned. We hope to get started on this in the coming weeks.

**Comment by dpoole73** [comment]
Do you have an estimate of when this might be available?

**Comment by okke-formsma** [comment]
This is currently blocking our upgrade to 6.0. When do you know when this will be implemented?

**Comment by russcam** [comment]
@dpoole73 @okke-formsma I've started looking at supporting 6.x this week.
