### ISSUE TITLE
Elasticsearch Initialization failed

### ISSUE THREAD

**Issue by ravitejag** [elastic/azure-marketplace#153]
With Xpack Plugins disabled and LoadBalancer as "gateway". ES fails to start with the following error

`Suppressed: java.lang.IllegalArgumentException: unknown setting [xpack.security.authc.anonymous.authz_exception] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`
`Suppressed: java.lang.IllegalArgumentException: unknown setting [xpack.security.authc.anonymous.username] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`
`Suppressed: java.lang.IllegalArgumentException: unknown setting [xpack.security.authc.anonymous.roles] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`

Is there a way to avoid this?

**Comment by russcam** [comment]
Thanks for opening this issue @ravitejag. 

This looks like a bug in that [the template always attempts to set anonymous access when the load balancer type is `gateway`](https://github.com/elastic/azure-marketplace/blob/master/src/mainTemplate.json#L1152), however, anonymous access can only be configured when X-Pack is installed.

We'll address this in the next release. In the meantime, you can workaround this by removing [the anonymous access configuration](*https://github.com/elastic/azure-marketplace/blob/master/src/scripts/elasticsearch-ubuntu-install.sh#L680-L685) from elasticsearch.yml on each node in the cluster. The configuration file can be found at `/etc/elasticsearch/elasticsearch.yml`

**Comment by russcam** [comment]
@ravitejag [I've released 5.6.5 with this fix.](https://github.com/elastic/azure-marketplace/tree/5.6.5). It is recommended to target that release branch/tag for repeatable deployments.

 Thanks again!
