### ISSUE TITLE
Deploy Logstash as part of the template

### ISSUE THREAD

**Issue by russcam** [elastic/azure-marketplace#157]

**Comment by raviada** [comment]
Yes, I agree. Otherwise what would be the recommended approach to install logstash in this cluster?
Thanks

**Comment by russcam** [comment]
@raviada The easiest approach for the moment would be to:

1. Create a VM
2. Attach it to the same VNet as the Elasticsearch cluster 
3. Install Logstash onto the VM

**Comment by mario-paniccia** [comment]
any progress on this? It'll be very useful

**Comment by in4margaret** [comment]
@mario-paniccia ,  https://in4margaret.github.io/example/2018-08-19-logstash-azure/

**Comment by russcam** [comment]
great post @in4margaret !

@mario-paniccia I started on adding logstash in  https://github.com/elastic/azure-marketplace/tree/feature/logstash but have had to park it for the moment to prioritize the .NET clients and Windows installers. Hoping to pick it up again in the next few weeks; the branch needs rebasing against master too.

**Comment by mario-paniccia** [comment]
great article @in4margaret thanks!
Hope to see this released soon @russcam in our project I'm currently building a Logstash image with Packer but it's not ideal
