### ISSUE TITLE
apt package oracle-java-8-installer broken

### ISSUE THREAD

**Issue by russcam** [elastic/azure-marketplace#159]
The apt package that is used to install Java 8 is currently broken; it attempts to download an installer for Java 8u151 which is no longer listed on the Oracle website.

Whilst the package is convenient for installation, it does seem that there is some delay between a new version of the JDK released and the apt package updated. We should look at alternative ways to install Java 8 that do not rely on the oracle-java-8-installer package.

**Comment by russcam** [comment]
@lmemmott The issue has been closed because it is now resolved. A new version of the template went live on the Azure Marketplace on Saturday 20 January 2018 at 05:19 AEST with #160 applied, which includes the fix for the apt package. I don't know how Azure infrastructure roles out changes to different regions, it could be possible that the template is incrementally rolled out after going live.

To know if you're using the latest version of the template on the Marketplace, the default Elasticsearch version will be v5.6.6.

You can also consume the ARM template directly from here, by targeting the [5.6.6](https://github.com/elastic/azure-marketplace/tree/5.6.6) tag.

**Comment by lmemmott** [comment]
FYI, a new test run yesterday passed.  It looks like the issue has been corrected.

**Comment by russcam** [comment]
Thanks for reporting back @lmemmott
