### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by FKorni** [elastic/azure-marketplace#162]
I have tried multiple times to to create a elasticsearch cluster with your template but it always fails.
It seems that there is some problem with installing Java on the VMs.

` 
statusMessage:{"status":"Failed","error":{"code":"ResourceOperationFailure","message":"Der Ressourcenvorgang wurde mit Bereitstellungsendzustand \"Failed\" abgeschlossen.","details":[{"code":"VMExtensionProvisioningError","message":"Der virtuelle Computer hat beim Verarbeiten der Erweiterung \"script\" einen Fehler gemeldet. Fehlermeldung: \"Enable failed: failed to execute command: command terminated with exit status=50\n[stdout]\nu3 [22.4 kB]\nGet:8 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 xfonts-encodings all 1:1.0.4-2 [573 kB]\nGet:9 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 xfonts-utils amd64 1:7.7+3ubuntu0.16.04.2 [74.6 kB]\nGet:10 http://azure.archive.ubuntu.com/ubuntu xenial/universe amd64 gsfonts-x11 all 0.24 [7,314 B]\nFetched 4,208 kB in 0s (46.0 MB/s)\nSelecting previously unselected package java-common.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 61525 files and directories currently installed.)\r\nPreparing to unpack .../java-common_0.56ubuntu2_all.deb ...\r\nUnpacking java-common (0.56ubuntu2) ...\r\nSelecting previously unselected package oracle-java8-installer.\r\nPreparing to unpack .../oracle-java8-installer_8u151-1~webupd8~0_all.deb ...\r\ndebconf: unable to initialize frontend: Dialog\r\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\r\ndebconf: falling back to frontend: Readline\r\noracle-license-v1-1 license has already been accepted\r\nUnpacking oracle-java8-installer (8u151-1~webupd8~0) ...\r\nProcessing triggers for man-db (2.7.5-1) ...\r\nProcessing triggers for mime-support (3.59ubuntu1) ...\r\nProcessing triggers for shared-mime-info (1.5-2ubuntu0.1) ...\r\nSetting up java-common (0.56ubuntu2) ...\r\nSetting up oracle-java8-installer (8u151-1~webupd8~0) ...\r\ndebconf: unable to initialize frontend: Dialog\r\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\r\ndebconf: falling back to frontend: Readline\r\nUsing wget settings from /var/cache/oracle-jdk8-installer/wgetrc\r\nDownloading Oracle Java 8...\r\n--2018-01-19 16:51:39-- http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz\r\nResolving download.oracle.com (download.oracle.com)... 2.18.227.187\r\nConnecting to download.oracle.com (download.oracle.com)|2.18.227.187|:80... connected.\r\nHTTP request sent, awaiting response... 302 Moved Temporarily\r\nLocation: https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz [following]\r\n--2018-01-19 16:51:39-- https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz\r\nResolving edelivery.oracle.com (edelivery.oracle.com)... 2.19.148.207, 2a02:26f0:6b:291::2d3e, 2a02:26f0:6b:294::2d3e\r\nConnecting to edelivery.oracle.com (edelivery.oracle.com)|2.19.148.207|:443... connected.\r\nHTTP request sent, awaiting response... 302 Moved Temporarily\r\nLocation: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516380820_dbeef7a4f83bf962ce8520d1553b405b [following]\r\n--2018-01-19 16:51:40-- http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1516380820_dbeef7a4f83bf962ce8520d1553b405b\r\nConnecting to download.oracle.com (download.oracle.com)|2.18.227.187|:80... connected.\r\nHTTP request sent, awaiting response... 404 Not Found\r\n2018-01-19 16:51:41 ERROR 404: Not Found.\r\n\r\ndownload failed\r\nOracle JDK 8 is NOT installed.\r\ndpkg: error processing package oracle-java8-installer (--configure):\r\n subprocess installed post-installation script returned error exit status 1\r\nErrors were encountered while processing:\r\n oracle-java8-installer\r\n[19012018-16:51:42] [install_java] Seeing if java is Installed after nuclear retry 30/30\n[19012018-16:51:42] installing Elasticsearch returned exit code 50\n\n[stderr]\n\ngpg: key EEA14886: public key \"Launchpad VLC\" imported\ngpg: no ultimately trusted keys found\ngpg: Total number processed: 1\ngpg: imported: 1 (RSA: 1)\ndebconf: unable to initialize frontend: Dialog\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \nE: Sub-process /usr/bin/dpkg returned an error code (1)\ngpg: keyring `/tmp/tmph0x5drjv/secring.gpg' created\ngpg: keyring `/tmp/tmph0x5drjv/pubring.gpg' created\ngpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmph0x5drjv/trustdb.gpg: trustdb created\ngpg: key EEA14886: public key \"Launchpad VLC\" imported\ngpg: no ultimately trusted keys found\ngpg: Total number processed: 1\ngpg: imported: 1 (RSA: 1)\ndebconf: unable to initialize frontend: Dialog\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \nE: Sub-process /usr/bin/dpkg returned an error code (1)\ngpg: keyring `/tmp/tmpjn18998o/secring.gpg' created\ngpg: keyring `/tmp/tmpjn18998o/pubring.gpg' created\ngpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmpjn18998o/trustdb.gpg: trustdb created\ngpg: key EEA14886: public key \"Launchpad VLC\" imported\ngpg: no ultimately trusted keys found\ngpg: Total number processed: 1\ngpg: imported: 1 (RSA: 1)\ndebconf: unable to initialize frontend: Dialog\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \nE: Sub-process /usr/bin/dpkg returned an error code (1)\ngpg: keyring `/tmp/tmp21n8cn3d/secring.gpg' created\ngpg: keyring `/tmp/tmp21n8cn3d/pubring.gpg' created\ngpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmp21n8cn3d/trustdb.gpg: trustdb created\ngpg: key EEA14886: public key \"Launchpad VLC\" imported\ngpg: no ultimately trusted keys found\ngpg: Total number processed: 1\ngpg: imported: 1 (RSA: 1)\ndebconf: unable to initialize frontend: Dialog\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \nE: Sub-process /usr/bin/dpkg returned an error code (1)\ngpg: keyring `/tmp/tmp3sktofs9/secring.gpg' created\ngpg: keyring `/tmp/tmp3sktofs9/pubring.gpg' created\ngpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmp3sktofs9/trustdb.gpg: trustdb created\ngpg: key EEA14886: public key \"Launchpad VLC\" imported\ngpg: no ultimately trusted keys found\ngpg: Total number processed: 1\ngpg: imported: 1 (RSA: 1)\ndebconf: unable to initialize frontend: Dialog\ndebconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)\ndebconf: falling back to frontend: Readline\ndebconf: unable to initialize frontend: Readline\ndebconf: (This frontend requires a controlling tty.)\ndebconf: falling back to frontend: Teletype\ndpkg-preconfigure: unable to re-open stdin: \nE: Sub-process /usr/bin/dpkg returned an error code (1)\n[19012018-16:51:42] Java did not get installed properly even after a retry and a forced installation\n\"."}]}}`

3 weeks ago I hade no problem with this and everything worked fine.
Probably this duplicates #159 and the changes are not in the Azure marketplace yet..

**Comment by josh-klassen** [comment]
I am also seeing this same issue. Do we know if there is an ETA on the fix?

**Comment by russcam** [comment]
This should now be fixed in both the Azure Marketplace and in the template here by #160. I received a notification that the new version of the offering is now live with this change. 

Please try deploying from the Marketplace again and if the problem persists, feel free to reopen this. Thanks!
