### ISSUE TITLE
Removing X-Pack and Apply Free license

### ISSUE THREAD

**Issue by MattHartz** [elastic/azure-marketplace#164]
Hi all,

Up until recently, I have been running version 2.4 iirc, and decided to upgrade to 5.X since it's not supported anymore when rebuilding a cluster.

Part of the usual process is to run a CURL command to apply the basic license to elasticsearch, the disable shield.  

Because the elastic stack seems to be a little different, I am running this command
curl -XPUT -u elastic "http://<URL>:<PORT>/_xpack/license" -H "Content-Type: application/json" -d @json.json

Then after that, I am trying to follow the uninstall steps guided by https://www.elastic.co/guide/en/x-pack/5.4/installing-xpack.html.

After doing so, when trying to start elasticsearch, it starts throwing the error about NoSuchFileException "/user/share/elasticsearch/config", but the config file is in "etc/Elasticsearch"

Did I do something wrong in these steps to cause elasticsearch to go crazy?
Thanks!

**Comment by russcam** [comment]
Hi @MattHartz, let me see if I can help.

>  Up until recently, I have been running version 2.4 iirc, and decided to upgrade to 5.X since it's not supported anymore when rebuilding a cluster.

It sounds like you may be deploying a cluster from the Azure Marketplace directly? This is fine of course, but I would recommend [deploying the cluster from this github repository directly](https://www.elastic.co/blog/elasticsearch-and-kibana-deployments-on-azure), targeting a specific version tag if intending to take to production. The reason for recommending this approach is that the Marketplace offering is the latest release of the template only and therefore for repeatable deployments, targeting a specific version is a good idea.

> Because the elastic stack seems to be a little different, I am running this command
> curl -XPUT -u elastic "http://:/_xpack/license" -H "Content-Type: application/json" -d @json.json
> 
> Then after that, I am trying to follow the uninstall steps guided by https://www.elastic.co/guide/en/x-pack/5.4/installing-xpack.html.

In applying a basic license, I'm not sure why X-Pack then needs to be uninstalled? The basic license works with X-Pack. Can you elaborate on why you're uninstalling X-Pack? X-Pack Security is not supported with a basic license so it _should_ be disabled by default after license application and restarting the node.

> After doing so, when trying to start elasticsearch, it starts throwing the error about NoSuchFileException "/user/share/elasticsearch/config", but the config file is in "etc/Elasticsearch"

The Elasticsearch service is controlled through monit currently. How are you stopping and restarting Elasticsearch?

**Comment by MattHartz** [comment]
Hi @russcam ,
In the older version elasticsearch/kibana azure package, when adding a basically license, i still had to and remote into machines and actually turn off some settings on the vms. 

Shield.Enabled iirc.

So if I apply the basic license, how can i then also remove the security features of my cluster?  I know this is not a good thing, it's just for temporary reasons. Also, after the 1 month trial of x-pack, will all the features safely stop working?  Before after the month expired, if i didn't go through the whole cluster setting shield.enabled to false, I would lose access to Kibana.

**Comment by MattHartz** [comment]
@russcam But yeah, I just wanna apply the basic license and know for sure that after the x-pack trial expires that Kibana and Elasticsearch will continue to function. Do I need to restart the node after applying the license and if so, whats the best course of action? I was having issues when restarting the elasticsearch service.

**Comment by MattHartz** [comment]
@russcam Okay, so i think i was applying the basic license without the acknowledgement.  It looks like it works.. Thanks!

**Comment by russcam** [comment]
glad you got it sorted @MattHartz 👍
