### ISSUE TITLE
[elastic6] Azure-repository settings should be set using keystore

### ISSUE THREAD

**Issue by okke-formsma** [elastic/azure-marketplace#167]
After deploying the elastic6 template, it is currently impossible to restore backups. This is caused by a known issue(https://github.com/elastic/elasticsearch/issues/28299#issuecomment-358703209), but the proper solution is to save the azure.client.default.account and azure.client.default.key in the keystore isntead of elasticsearch.yml.

**Comment by dadoonet** [comment]
For the record I just sent a PR to fix that problem. See https://github.com/elastic/elasticsearch/pull/28769
