### ISSUE TITLE
Fully Managed PaaS solution

### ISSUE THREAD

**Issue by pvanroos** [elastic/azure-marketplace#170]
Is the Azure team considering turning ELK into a fully managed PaaS solution like what AWS has?

**Comment by russcam** [comment]
Azure has a managed PaaS service in the form of [Azure Search](https://azure.microsoft.com/en-us/services/search/) so I wouldn't imagine another search service appearing, although that's a question best answered by Microsoft. 

I can tell you that we're working on bringing [Elastic Cloud](https://www.elastic.co/cloud) to Azure, to offer the best Elasticsearch as a Service experience. No definite timeline for when this will be ready as yet but stay tuned.
