### ISSUE TITLE
remove old logs

### ISSUE THREAD

**Issue by okke-formsma** [elastic/azure-marketplace#172]
The current logging configuration will happily keep on logging until the logging disk runs out of space.

Please add something like the following configuration to the logging:

```appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.fileIndex = nomax
appender.rolling.strategy.action.type = Delete 
appender.rolling.strategy.action.basepath = ${sys:es.logs.base_path}
appender.rolling.strategy.action.condition.type = IfFileName 
appender.rolling.strategy.action.condition.glob = ${sys:es.logs.cluster_name}-* 
appender.rolling.strategy.action.condition.nested_condition.type = IfAccumulatedFileSize 
appender.rolling.strategy.action.condition.nested_condition.exceeds = 2GB 
```
So logging won't kill the machine over time by default.

**Comment by russcam** [comment]
@okke-formsma Thanks for opening this issue 👍 

The current log configuration errs on the side of not deleting any log files, which feels like a better default to have over one that deletes files.

I think the approach we might want to take here would be to first better document what the current log configuration is, so users are aware of it. Then, possibly provide a parameter to the template to allow a custom log configuration to be specified. At the moment, the logging configuration can be changed on each VM within the cluster, but doing manually for a larger cluster can be onerous. It's a case of striking the right balance in the template with regards to parameters and template complexity; the template has 59(!) input parameters to it thus far, and there will likely be more as we look to incorporate logstash into it.

**Comment by okke-formsma** [comment]
@russcam Thanks for your response. I'm not sure I agree about the better default; the defaults for e.g. Ubuntu are to delete log files after some time [0].

Anyway, a configuration section that would be appended to the log4j config file would be a great starting point, just like the "esAdditionalYaml" parameter. ("log4jAdditionalYaml"?)

0: https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04

**Comment by russcam** [comment]
The default logging policy was changed in 6.0+ in https://github.com/elastic/elasticsearch/pull/25660 to

- compress rolled logs
- roll logs every 128 MB
- maintain a sliding window of logs
- remove the oldest logs maintaining no more than 2 GB of compressed logs on disk

The 5.x logging policy does not have these changes, so the log files continue to grow.

**Comment by okke-formsma** [comment]
Awesome, thank you.
