### ISSUE TITLE
Passwords not being set via ARM Template

### ISSUE THREAD

**Issue by robertmarks** [elastic/azure-marketplace#173]
When using the template for custom deployment it fails to set the password for the user 'elastic' during deployment and uses the default 'changeme'

**Comment by russcam** [comment]
@robertmarks Would you be able to provide some additional information?

- do you have the log file from `/var/log/arm-install.log`?
- what template version are you using?
- what version of Elasticsearch are you deploying?
- do you have a set of template parameters that reproduces the issue?

**Comment by russcam** [comment]
I've run several deployments today but am not seeing this issue. 

@robertmarks would you mind trying to deploy again from the master branch, commit e89baf2bd4fe9f8978aadcbae3eb3776435c598c ?

**Comment by robertmarks** [comment]
This is now working when we use it via Azure CLI so closing the issue 👍 

Not sure what caused it previously - redeployed instead.

**Comment by russcam** [comment]
Thanks for reporting back @robertmarks, and good to hear it's working for you :+1:
