### ISSUE TITLE
Error whiling creating ES cluster via Azure portal 

### ISSUE THREAD

**Issue by cloudmelon** [elastic/azure-marketplace#174]
While creating a Elastic search cluster via Azure portal ,  new resource == > Elastic Stack - (Elasticsearch, Kibana, X-Pack)  ===> 1 master node ( small D series ), then 20 data nodes ( DS series ) ,  this error :

![image](https://user-images.githubusercontent.com/4621560/38316636-8161d856-382b-11e8-9633-3999b4af155d.png)

Then change to another subscription , the deployment is ok, but the same error displays in console : 
![image](https://user-images.githubusercontent.com/4621560/38317429-5b1d8b2a-382d-11e8-9e22-3fb3e23a04fa.png)

**Comment by russcam** [comment]
@cloudmelon The first screenshot indicates that the template you're attempting to deploy has failed the Marketplace validation process as you have a maximum of 20 VM cores in the subscription/region, are already using 10, and are requesting an additional 23 cores. To resolve, you will need to speak to Microsoft about requesting an increase in the number of VM cores available in that subscription/region and possibly VM SKU that you are deploying.

The error messages in the browser console are related to Microsoft Azure portal JavaScript code and not with the Elastic Azure ARM template. I would suggest raising a ticket with Microsoft support to make them aware of the issue, and send them a screenshot 👍

**Comment by russcam** [comment]
@cloudmelon The first screenshot indicates that the template you're attempting to deploy has failed the Marketplace validation process as you have a maximum of 20 VM cores in the subscription/region, are already using 10, and are requesting an additional 23 cores. To resolve, you will need to speak to Microsoft about requesting an increase in the number of VM cores available in that subscription/region and possibly VM SKU that you are deploying.

The error messages in the browser console are related to Microsoft Azure portal JavaScript code and not with the Elastic Azure ARM template. I would suggest raising a ticket with Microsoft support to make them aware of the issue, and send them a screenshot 👍

**Comment by cloudmelon** [comment]
Thank you! you're right I'll check that with Microsoft portal team.
