### ISSUE TITLE
How to integrate to Azure Active Directory

### ISSUE THREAD

**Issue by DanielWangZhanggui** [elastic/azure-marketplace#179]
Greetings, 

Just wondering if we can integrate Elastic Stack to Azure Active Directory, so that we can configure permissions on Azure Active Directory.  Thanks!

All the best,
Daniel

**Comment by russcam** [comment]
Hey @DanielWangZhanggui - It's possible to do with X-Pack and I'm working on a blog post to share details on how to do this.

**Comment by DanielWangZhanggui** [comment]
Cool! Looking forward it. :-D


All the best,
Daniel

**Comment by russcam** [comment]
@DanielWangZhanggui [the blog post is now live: ](https://www.elastic.co/blog/saml-based-single-sign-on-with-elasticsearch-and-azure-active-directory?blade=tw&hulk=social)

**Comment by alexknipfer** [comment]
Hey @russcam, great blog post, currently trying to configure SAML SSO with Azure AD. We have an existing elastic stack deployed on azure (we used the template from the marketplace), the only place I'm confused on in your blog post is setting `samlMetadataUri` and `samlServiceProviderUri`, can these be configured after it's been deployed, if so, how do I got about configuring these values?

Thank you!
Alex

**Comment by russcam** [comment]
Hey @alexknipfer, `samlMetadataUri` and `samlServiceProviderUri` are input parameters to the ARM template that are not exposed in the Azure Marketplace offering - this is a deliberate decision, to keep the Marketplace getting started experience as simple as possible.

If you've already deployed Elasticsearch, you'll need to edit the elasticsearch.yml config on each node in the cluster for SAML integration. Perhaps the most straightforward way to understand what is required would be to check out the elasticsearch installation script does:

https://github.com/elastic/azure-marketplace/blob/59afd796c21c05188e50b3aea6dfd261c3147636/src/scripts/elasticsearch-ubuntu-install.sh#L1081-L1105

as well as the kibana install script

https://github.com/elastic/azure-marketplace/blob/59afd796c21c05188e50b3aea6dfd261c3147636/src/scripts/kibana-install.sh#L285-L302

**Note**, all the prerequisites listed in the blog post apply e.g. Kibana must be installed, license applied must be one that enables the SAML realm, TLS for Elasticsearch HTTP layer, Elasticsearch version must be equal or greater than 6.2.0, etc.

Another option may be to deploy a new cluster, snapshot data from the existing cluster, and restore to the new cluster. [We're working on documentation for the ARM template, including a section on SAML.](https://github.com/elastic/azure-marketplace/blob/feature/docs/docs/azure-arm-template.asciidoc#saml-single-sign-on-with-azure-active-directory)

Hope that helps!
