### ISSUE TITLE
how to access elasticsearch.yml?

### ISSUE THREAD

**Issue by AlphaOmegaFirstLast** [elastic/azure-marketplace#185]
I installed kibana+elastic search template (trial) with external loadbalancer option
I would like to allow Cors on elasticsearch so I can access it via the external load balancer.
It seems there is no UI in the template to  access elasticsearch.yml.
it seems to me the only way to acess it is through connecting to elastic virtual machine.
How I can do this and do I need to set it in only one virtual machine or more than one virtual machine ?
thanks

**Comment by russcam** [comment]
You will need to 

1. ssh into each VM running an Elasticsearch node
2. update Elasticsearch.yml in `/etc/elasticsearch/elasticsearch.yml`
3. restart the service through monit with `monit restart elasticsearch`

The external load balancer does not expose a port to allow ssh, but the Kibana public IP address does so you can use the Kibana VM as a jumpbox to ssh into the Elasticsearch nodes

```sh
ssh <kibana IP address or domain>
```
then once connected
```sh
ssh data-0
```
etc., to ssh into each node.

If you're deploying the template from this GitHub repository (which I would recommend for production, targeting a specific tagged release), you can specify additional elasticsearch YAML configuration with the [`esAdditionalYaml` parameter](https://github.com/elastic/azure-marketplace#parameters).

I hope this helps.
