### ISSUE TITLE
repository-azure: repository_verification_exception

### ISSUE THREAD

**Issue by tdoman** [elastic/azure-marketplace#186]
ES 6.1.1
repository-azure 6.1.1

Since February, we have been using ES 6.1.1 w/ repository-azure 6.1.1 successfully in all dev lanes and production to take snapshots.  About a week or two ago, we started receiving errors on our nightly attempts to take snapshots in our production environment only.  Here's what we see:

**Request:**
```
PUT _snapshot/es-2018-05?pretty=true
{
  "settings": {
    "container": "elasticsearch-backups",
    "base_path": "es-2018-05",
    "compress": true,
    "chunk_size": "64mb"
  },
  "type": "azure"
}
```
**Response:**
```
{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[es-2018-05] path [es-2018-05] is not accessible on master node"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[es-2018-05] path [es-2018-05] is not accessible on master node",
    "caused_by": {
      "type": "i_o_exception",
      "reason": "Can not write blob master.dat-temp",
      "caused_by": {
        "type": "storage_exception",
        "reason": "storage_exception: The specified resource does not exist."
      }
    }
  },
  "status": 500
}
```
I saw here [Azure-keystore credentials not set](https://github.com/elastic/azure-marketplace/issues/180) that @russcam was seeing the same thing when the credentials weren't set so I went and removed and re-added the `azure.client.default.account` and `azure.client.default.key` values on each node in my 3 node cluster in case they had somehow become corrupted but to no avail.  I did not restart my instances after assuming the plugin just reads them on each request.  One thing I can't do is get it to show me the values I believe I'm entering (ie. since keystore add doesn't show the input on the screen) but I've done it the same way on each system and, again, it had been working just fine previously.
I have no idea why it should, of a sudden, stop working when it was working just fine for 3 months.  I did verify that the key had not changed.  I can access the storage account w/ the CloudBerry Explorer just fine.  The `elasticsearch-backups` container exists (as it has from the beginning) and the above `PUT` has always caused that folder to be created if it didn't already exist.  As I was saying, this continues to work in my lower dev lane's clusters so I'm stumped.

**Comment by tdoman** [comment]
As I was saying earlier, I had not restarted any of my instances so I decided to embark on a rolling restart just to see if that'd resolve my issue.  After I had restarted two of the nodes, the one that was master and previously had all the primary replicas had moved the responsibility to node I hadn't yet restarted.  So, I decided to go ahead and try the request shown above again just to see if it was perhaps something node specific.  Sure enough, it worked.  So, I'm left to assume that the node that had become the master and received all the primaries from previous restarts (windows OS updates, etc.) was misconfigured (perhaps I fat fingered the key?) and that, if now it was to become so again, it would be properly configured and the snapshots would continue as expected.  I remain unsure if updating the keystore requires a restart.

**Comment by russcam** [comment]
Glad to hear that you got it resolved @tdoman. I _believe_ repository-azure plugin reads credentials from the keystore only on first usage, @dadoonet is this correct?

**Comment by dadoonet** [comment]
This is correct. But I saw some recent changes where we are going to support hot reloading of credentials.
It's possible though to create a new client with new credentials and use that new client by recreating the repository. That should read the new credentials I believe.
