### ISSUE TITLE
Data-Node Deployments failing due to Fault Domain Setting

### ISSUE THREAD

**Issue by robertmarks** [elastic/azure-marketplace#189]
New deployments of Elastic are failing to deploy data-nodes due to the Fault Domain Setting being invalid.

Command for deployment: 
`az group deployment create -g "demo2-elastic" -n "demo2-elastic-fri25" --template-uri "https://raw.githubusercontent.com/elastic/azure-marketplace/master/src/mainTemplate.json" --parameters @demo-elastic.json`

Error:
`The specified fault domain count 3 must fall in the range 1 to 2. (Code: InvalidParameter, Target: platformFaultDomainCount)`

This is for a single node master/data setup using app gateway.

**Comment by russcam** [comment]
@robertmarks Thanks for reporting. 

Please could you [target a specific tag version of the template](https://github.com/elastic/azure-marketplace/tree/master#targeting-a-specific-template-version) e.g. 6.2.4. master branch has changes that are not yet released, including a change to using managed disks, which is what I think may be causing this issue.

Let me know how 6.2.4 goes.

**Comment by russcam** [comment]
Meant to ask - What location are you deploying to?

**Comment by panyang1217** [comment]
I think this problem is caused by the fault domain limit in specific location. 
I've found this problem in SouthAsia region in Global Azure and all region in China Azure.
So i think you can change the location to another region that support more fault domain if you can. Or you have to change all av-set configuration "platformFaultDomainCount" to 2 , in the template, on your owen branch.

**Comment by robertmarks** [comment]
@russcam I'm deploying to UK South which was working fine previously.

I tried to target 6.2.4 using the following:
`az group deployment create -g "demo2-elastic" -n "demo2-elastic-fri25" --template-uri "https://raw.githubusercontent.com/elastic/azure-marketplace/6.2.4/src/mainTemplate.json" --parameters @demo-elastic.json`

This fails with the following error that I have yet to troubleshoot:
`Deployment failed. Correlation ID: ba93b7d1-63cc-474f-96e5-cc74227664a5. {
  "error": {
    "code": "InvalidTemplate",
    "message": "Deployment template validation failed: 'The template variable 'commonInstallParams' is not valid: The language expression property 'suffix' doesn't exist, available properties are 'name, key, install'.. Please see https://aka.ms/arm-template-expressions for usage details.'."
  }
}`
The params json file that I'm using worked previously just using the master src branch deployment so I don't think it's that causing the issue.

@panyang1217 I'll try that change - I've not seen this issue previously doing this deployment (I have it deployed for another env in exactly the same way).

**Comment by robertmarks** [comment]
Update: When doing a targeted deployment using the below of 6.2.4 via Powershell on Win 10:
`New-AzureRmResourceGroupDeployment -Name "test" -ResourceGroupName "demo2-elastic" -TemplateUri "$templateBaseUrl/mainTemplate.json" -TemplateParameterObject $clusterParameters`
Deploys fine and works as expected with the same settings just in an array.

Interesting that a targeted deployment on Mac PowerShell fails using the same set of settings in a JSON file/template-uri pointed toward 6.2.4
