### ISSUE TITLE
Kibana fails to start if password contains '!' character

### ISSUE THREAD

**Issue by sukrit007** [elastic/azure-marketplace#197]
We have an '!' character in kibana. This failed the kibana startup with following error: 

`
FATAL CLI ERROR YAMLException: unknown tag !<!*************> at line 7, column 1:
Jun 27 23:11:06 eskibana kibana[3411]:     xpack.security.encryptionKey: "L ...
Jun 27 23:11:06 eskibana kibana[3411]:     ^
`
**Deployment**:
Web based deploy:  https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Felastic%2Fazure-marketplace%2Fmaster%2Fsrc%2FmainTemplate.json

**Git Branch**: master

**Parameters**:
All parameters were specified using UI.  
Kibana Username:  kibana
Kibana Password: !***********

**Comment by russcam** [comment]
@sukrit007 Could you please provide more information

- how are you deploying the template
- what git branch are you targeting
- what parameters are you providing (please obfuscate sensitive parameters)
- could you provide the `var/logs/arm-install.log` from the Kibana VM

**Comment by russcam** [comment]
Thanks @sukrit007. This issue has been fixed in #187. In the meantime and as a workaround, avoid starting a password with `!`.

I would recommend that you not deploy from the master branch as it may contain changes that are not yet deemed finished for a release.
