### ISSUE TITLE
kibana install script must install version of the marvel plugin supported by the cluster

### ISSUE THREAD

**Issue by trentmswanson** [elastic/azure-marketplace#2]
The kibana installation script currently installs the __latest__ version of the marvel plugin, which happens to be 2.1 as or right now.  This version of the plugin seems to be incompatible with a 2.0.1 cluster. The script needs to install an explicit version of the plugins to ensure they are compatible with the whatever is installed in the cluster.

**Comment by Mpdreamz** [comment]
Thanks for raising this @trentmswanson, 

Elasticsearch plugin management has an automatic mechanism to ensure the version of the plugin is installed, when you install an official plugin. Kibana does not (yet), we'll need to find a way to map this appropiately.

**Comment by skearns64** [comment]
@Mpdreamz - I think we actually need to make sure that the template deploys "matching versions" of ES + Kibana as well. By matching version, I mean the versions that were released at the same time: ES 2.0 -> Kibana 4.2. ES 2.1 -> Kibana 4.3. 

If we tie things this way, we'll make sure that Marvel always works as well, and will keep people tied to compatible, well-tested version combinations.

**Comment by trentmswanson** [comment]
You could define version mappings as a variable in the top level template or someplace easy to maintain, then pass those values along to the script.  At least his is how I believe I will resolve this in the quickstart template.

```
"versionsSettings": {
      "2.0.1" : {
        "kibana": "2.0.0",
        "marvel": "2.0.0"
      },
      "2.1.0" : {
        "kibana": "2.1.0",
        "marvel": "2.1.0"
      }
    }
```

Then select it using something like `[variables('versionSettings')[parameters('esVersion')].kibana]` to pass to the child templates and scripts.

**Comment by Mpdreamz** [comment]
++ @trentmswanson exactly what I was thinking :+1: 

We have a special [allowedValues.json](https://github.com/elastic/azure-marketplace/blob/master/src/allowedValues.json#L2) that we use to patch the marketplace UI and the arm template at build them that we should extend to also include the kibana/marvel mapping.
