### ISSUE TITLE
Issue with Elasticstack on Azure...permission

### ISSUE THREAD

**Issue by dbclkclk** [elastic/azure-marketplace#202]
I'm deployed ElasticStack on Azure however, I'm getting issues connecting Kibana to ElasticSearch. Currently I'm getting errors `action [indices:data/read/search] is unauthorized for user [kibana]`. I've gone as far as to ssh into the kibana server and change ElasticSearch connection user from kibana to elastic (kibana.yml) however, I'm still getting the error.

**Comment by russcam** [comment]
@dbclkclk Could you please provide more information

- how are you deploying the template e.g. Azure Marketplace, CLI 1.0, 2.0, PoweShell
- what git branch are you targeting
- what parameters are you providing (please obfuscate sensitive parameters)
- could you also provide the `/var/log/arm-install.log` from the Kibana VM and each Elasticsearch node

**Comment by dbclkclk** [comment]
@russcam  figured it out. I needed to login (through Kibana) with the `elastic` user. I was logging into Kibana with the `kibana` user which was causing the issue.
