### ISSUE TITLE
How to install LogStash plugin on Azure

### ISSUE THREAD

**Issue by dbclkclk** [elastic/azure-marketplace#204]
Hi:

I have deployed Elastic Stack on Azure using Microsoft Market Place template. At this point in time, I'm not sure how to install a plugin into LogStash and there doesn't seem to be a server running logstash that I can ssh into to for plugin installation.

**Comment by russcam** [comment]
Logstash is not installed as part of the template. There's an open issue #157 to track this. Closing this in favour of consolidating information there.

**Comment by dbclkclk** [comment]
@russcam  thank you. So the recommendation is to install this on a separate VM correct?

**Comment by russcam** [comment]
Correct.
