### ISSUE TITLE
Missing Azure Fsv2 VM Sizes

### ISSUE THREAD

**Issue by Viccen** [elastic/azure-marketplace#221]
Good morning,

I am currently not able to deploy an ES cluster using any of the  FsV2 machines (for example F2s_v2).

Could you please include this series as available sizes?
Is there any reason why this series is currently not supported?

Thanks in advance,
Victor

**Comment by russcam** [comment]
Hey @Viccen, we'll include the [FSv2-series in the next release ](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-compute#fsv2-series-sup1sup).

> Is there any reason why this series is currently not supported?

Looks like they were just overlooked the last time the allowed sizes were updated 😃

**Comment by Viccen** [comment]
Hi @russcam, thanks a lot for such a fast response. Can't wait for it 👍 !

**Comment by russcam** [comment]
I'll keep this issue open, to track it and link to.
