### ISSUE TITLE
Enable accelerated networking

### ISSUE THREAD

**Issue by Viccen** [elastic/azure-marketplace#224]
Good afternoon,

I am interested in enabling accelerated networking since we can benefit from lower network latencies. However I do not find how can I do it within the template. Is it supported?

Any advise?

Thanks,
Victor

**Comment by russcam** [comment]
Thanks for opening this issue @Viccen. I was not aware of accelerated networking, and after reading the docs, it looks like it would be very useful for a distributed system like Elasticsearch!

The template does not currently implement this, but it looks straightforward to include. I'm thinking of exposing it as a template parameter, with it defaulted to `Yes` for those VM SKUs that support it. Are there any cases where accelerated networking shouldn't be enabled?

**Comment by russcam** [comment]
@Viccen I've opened PR #230 to enable accelerated networking
