### ISSUE TITLE
Add out of the box monitoring via Application Insights

### ISSUE THREAD

**Issue by mario-paniccia** [elastic/azure-marketplace#227]
An issue we have with the current template is that it does not come with monitoring built in. 
To check the logfiles for errors, I have to ssh to the nodes and cat the logs. Once we deploy the cluster 
in production this will be difficult to do as only few people in our organisation have access to production. 
It's also quite cumbersome and time consuming in general.

Is it possible to update the template so it creates an instance of Azure Application Insights alongside the cluster?
And have the cluster publish health status and any errors and warns in the logs to Application Insights?
This way we can easily access this information via the Azure UI.

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-overview

**Comment by mario-paniccia** [comment]
Hi @russcam I see monitoring is not offered with the free basic license. Makes sense. 
Anyway I think adding Application Insights support in Monitoring would be beneficial for deployments on Azure, because Application Insights is the standard monitoring solution on Azure

**Comment by russcam** [comment]
There is a level of monitoring available under the free Basic license - check out under [Kibana > Stack Monitoring](https://www.elastic.co/subscriptions).

**Comment by mario-paniccia** [comment]
that really helped thanks @russcam

**Comment by russcam** [comment]
No worries @mario-paniccia . 

I'm going to close this issue as including Application insights in the template is unlikely to be implemented as a feature at this stage. Monitoring for the entire Elastic Stack is part of the stack features and enabled when `xPackPlugins` is set to `Yes` (the default).
