### ISSUE TITLE
configuration option to avoid ip address for kibana

### ISSUE THREAD

**Issue by mario-paniccia** [elastic/azure-marketplace#235]
at the moment if I chose to install Kibana the template assigns a public ip to it. 
But in my organisation this is a potential security issue and I need to manually remove it every time.
Is it possible to have a config parameter to avoid assigning a public ip to Kibana?

**Comment by russcam** [comment]
This is unlikely to be implemented as a feature of the main template, because other features of the template such as SAML authentication rely on there being a public IP address assigned for Kibana.

I would recommend removing the public IP address resource post-deployment.
