### ISSUE TITLE
Where to connect a Java client to?

### ISSUE THREAD

**Issue by mario-paniccia** [elastic/azure-marketplace#236]
With my configuration of the template I'm deploying a cluster with 2 data nodes, 2 master nodes and an internal load balancer.
Up until now I've been connecting my Java ES RestHighLevelClient to the load balancer via it's private ip. That seems to be working.
But now I'm wondering whether that's the ideal solution. 
Should I point instead to one of the master or data nodes?

**Comment by russcam** [comment]
You have two options @mario-paniccia:

1. Point at the internal load balancer as you are doing. The backend pool contains only data nodes (or coordinating nodes, if deploying those) and will round-robin requests across them. If you add more data nodes to the backend pool, these will be round-robin'ed across too.

2. Point to the collection of data nodes. All clients support a concept of sniffing, to pick up when new nodes have joined the cluster.

You shouldn't send requests to master nodes, and leave them to focus on managing cluster state.

**A side note:** A cluster running with 2 master nodes is **not recommended**, and runs the risk of [split brain](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#split-brain). You should run with a minimum of 3 master-eligible nodes, or 3 dedicated master nodes (as the template offers), for production for high availability and redundancy.

**Comment by mario-paniccia** [comment]
thanks @russcam 
regarding point 1, I always see the following exception from the client after a period of inactivity:
`"ElasticSearch initialisation exception:java.io.IOException: An existing connection was forcibly closed by 
 the remote host"`

You think that is caused by the loadbalancer having a default 5 min timeout on idle connections? If yes, any way I can sort this out by proper configuration of the client? 

regarding point 2, when you say 'Point to the collection of data nodes', is it ok if I point to only 1 of the data nodes?

**Comment by mario-paniccia** [comment]
very clear and useful @russcam, thanks!

**Comment by mario-paniccia** [comment]
very clear and useful @russcam thanks!
