### ISSUE TITLE
How to add additional nodes after the initial deployment

### ISSUE THREAD

**Issue by mario-paniccia** [elastic/azure-marketplace#238]
When I initially deploy the cluster I get to choose the number of data nodes that make up the cluster.
How can I add more data nodes for scalability after the initial deployment? Is it possible to do this without downtime?

**Comment by russcam** [comment]
@mario-paniccia Take a look at the documentation: https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-elasticsearch.html#azure-arm-template-scaling-nodes

As per the documentation, I would only use this when you have **dedicated master nodes**, and **not master-eligible nodes**; When using master-eligible nodes, the configuration on each node needs to be changed and the node restarted, which the Azure infrastructure will control.

**Comment by mario-paniccia** [comment]
@russcam I completely missed the ARM template documentation on www.elastic.co! Cheers
