### ISSUE TITLE
Add option to specify sku type for load balancers

### ISSUE THREAD

**Issue by mayuvara** [elastic/azure-marketplace#245]
Add option to specify sku type for load balancers

**Comment by mayuvara** [comment]
Here are some of features that we are looking for/ Basic SKUs do not support:
- Health probe on HTTPS
- Ability to add an availability set to the backend address pools and not individual nodes.
- Ability to add multiple availability sets and VMs across the Vnet not restricted to an availability set.
- Also, we have other services running on the same resource group that require a standard SKU configuration. Load balancers with different SKUs can not live together.
Azure also recommends using Standard SKUs for new designs.

**Comment by russcam** [comment]
#292 is merged. This will be in the next tagged release
