### ISSUE TITLE
${ELASTICSEARCH_URL} not defined

### ISSUE THREAD

**Issue by alcesleo** [elastic/azure-marketplace#256]
In the wizard there is a tooltip that says that you can use `${ELASTICSEARCH_URL}` to connect to ElasticSearch in your `logstash.conf`, however this doesn't seem to exist for me. When SSHing into the Logstash machine, no such environment variable is present (manually setting it to `10.0.0.4:9200` makes it work). I also had to manually set the password for the `elastic` user in the `logstash.conf` to get it to work, and then the `kibana` user doesn't seem to have access to any index - it does work when I log in with the `elastic` user in Kibana, but I have a feeling that this is not how it's meant to be. Could someone point me in the right direction in regards to where this went wrong?

**Comment by alcesleo** [comment]
Thank you for the thorough answer! It seems I misunderstood the purpose of the default roles, setting it up according to [this guide](https://www.elastic.co/guide/en/beats/filebeat/current/beats-basic-auth.html) helped me.

**Comment by 0GiS0** [comment]
Hi,

I'm trying to execute the lines you said:

set +o history
# export the keystore password into env variable
pass=$(sudo grep -Po "(?<=^LOGSTASH_KEYSTORE_PASS=).*" /etc/sysconfig/logstash)
export LOGSTASH_KEYSTORE_PASS=$pass
set -o history

# list keys in keystore
sudo -E /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash list

But I get this error:

ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/etc/logstash, exception=Java::OrgLogstashSecretStore::SecretStoreException::AccessException, message=>Can not access Logstash keystore at /etc/logstash/logstash.keystore. Please verify correct file permissions and keystore password.

[ERROR] 2019-10-01 07:28:23.048 [main] secretstorecli - Can not access Logstash keystore at /etc/logstash/logstash.keystore. Please verify correct file permissions and keystore password. {:cause=>java.io.IOException: Integrity check failed: java.security.UnrecoverableKeyException: Failed PKCS12 integrity checking, :backtrace=>["org.logstash.secret.store.backend.JavaKeyStore.load(org/logstash/secret/store/backend/JavaKeyStore.java:265)", "org.logstash.secret.store.backend.JavaKeyStore.load(org/logstash/secret/store/backend/JavaKeyStore.java:40)", "org.logstash.secret.store.SecretStoreFactory.doIt(org/logstash/secret/store/SecretStoreFactory.java:109)", "org.logstash.secret.store.SecretStoreFactory.load(org/logstash/secret/store/SecretStoreFactory.java:95)", "org.logstash.secret.cli.SecretStoreCli.command(org/logstash/secret/cli/SecretStoreCli.java:77)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:425)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:292)", "RUBY.<class:SecretStoreCli>(/usr/share/logstash/lib/secretstore/cli.rb:35)", "RUBY.<main>(/usr/share/logstash/lib/secretstore/cli.rb:16)", "org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:891)", "org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:895)", "org.jruby.Ruby.runNormally(org/jruby/Ruby.java:784)", "org.jruby.Ruby.runNormally(org/jruby/Ruby.java:797)", "org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:609)", "org.jruby.Main.doRunFromMain(org/jruby/Main.java:415)", "org.jruby.Main.internalRun(org/jruby/Main.java:307)", "org.jruby.Main.run(org/jruby/Main.java:234)", "org.jruby.Main.main(org/jruby/Main.java:206)"]}

any ideas?

Thanks!

**Comment by russcam** [comment]
@0GiS0 try with the `logstash` user

```sh
sudo -Eu logstash /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash list
```

**Comment by 0GiS0** [comment]
Hi Russ,

I get the same error :(

`gis@logstash-0:/usr/share/logstash$ sudo -Eu logstash /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash list

[ERROR] 2019-10-01 08:09:43.463 [main] secretstorecli - Can not access Logstash keystore at /etc/logstash/logstash.keystore. Please verify correct file permissions and keystore password. {:cause=>java.io.IOException: Integrity check failed: java.security.UnrecoverableKeyException: Failed PKCS12 integrity checking, :backtrace=>["org.logstash.secret.store.backend.JavaKeyStore.load(org/logstash/secret/store/backend/JavaKeyStore.java:265)", "org.logstash.secret.store.backend.JavaKeyStore.load(org/logstash/secret/store/backend/JavaKeyStore.java:40)", "org.logstash.secret.store.SecretStoreFactory.doIt(org/logstash/secret/store/SecretStoreFactory.java:109)", "org.logstash.secret.store.SecretStoreFactory.load(org/logstash/secret/store/SecretStoreFactory.java:95)", "org.logstash.secret.cli.SecretStoreCli.command(org/logstash/secret/cli/SecretStoreCli.java:77)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:425)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:292)", "RUBY.<class:SecretStoreCli>(/usr/share/logstash/lib/secretstore/cli.rb:35)", "RUBY.<main>(/usr/share/logstash/lib/secretstore/cli.rb:16)", "org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:891)", "org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:895)", "org.jruby.Ruby.runNormally(org/jruby/Ruby.java:784)", "org.jruby.Ruby.runNormally(org/jruby/Ruby.java:797)", "org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:609)", "org.jruby.Main.doRunFromMain(org/jruby/Main.java:415)", "org.jruby.Main.internalRun(org/jruby/Main.java:307)", "org.jruby.Main.run(org/jruby/Main.java:234)", "org.jruby.Main.main(org/jruby/Main.java:206)"]}
`

**Comment by russcam** [comment]
I think the exporting of the keystore pass may include the surrounding double quotes. Try this

```sh
set +o history
# export the keystore password into env variable
pass=$(sudo grep -Po "(?<=^LOGSTASH_KEYSTORE_PASS=).*" /etc/sysconfig/logstash | sed 's/"//g')
export LOGSTASH_KEYSTORE_PASS="$pass"
set -o history

# list keys in keystore
sudo -Eu logstash /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash list
```

**Comment by 0GiS0** [comment]
Thanks @russcam! 

Now It works:

```
gis@logstash-0:/usr/share/logstash$ set +o history
gis@logstash-0:/usr/share/logstash$ # export the keystore password into env variable
gis@logstash-0:/usr/share/logstash$ pass=$(sudo grep -Po "(?<=^LOGSTASH_KEYSTORE_PASS=).*" /etc/sysconfig/logstash | sed 's/"//g')
gis@logstash-0:/usr/share/logstash$ export LOGSTASH_KEYSTORE_PASS="$pass"
gis@logstash-0:/usr/share/logstash$ set -o history
gis@logstash-0:/usr/share/logstash$ 
gis@logstash-0:/usr/share/logstash$ # list keys in keystore
gis@logstash-0:/usr/share/logstash$ sudo -Eu logstash /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash list

elasticsearch_url
logstash_system_password
```

However, when I run this:

`sudo ./bin/logstash --setup --path.settings /etc/logstash/
`

I get a different error:

```
gis@logstash-0:/usr/share/logstash$ sudo ./bin/logstash --setup --path.settings /etc/logstash/
Thread.exclusive is deprecated, use Thread::Mutex
ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/etc/logstash/, exception=Java::OrgLogstashSecretStore::SecretStoreException::LoadException, message=>Found a file at /etc/logstash/logstash.keystore, but it is not a valid Logstash keystore.
[ERROR] 2019-10-01 08:30:17.611 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```


Thanks

**Comment by russcam** [comment]
Logstash installed by the template runs as a service managed by [systemd](https://www.freedesktop.org/wiki/Software/systemd/), so it should be started with

```sh
sudo systemctl start logstash.service
```

_If you do need to start it manually_, it should be started using the `logstash` user, and the keystore password needs to be exported as before (if not already exported)

```sh
set +o history
# export the keystore password into env variable
pass=$(sudo grep -Po "(?<=^LOGSTASH_KEYSTORE_PASS=).*" /etc/sysconfig/logstash | sed 's/"//g')
export LOGSTASH_KEYSTORE_PASS="$pass"
set -o history

sudo -Eu logstash /usr/share/logstash/bin/logstash --path.settings /etc/logstash --setup
```

Looking at the steps posted, it looks like you might be trying to configure the Logstash monitor module? [There's an example in the azure-marketplace-examples repository that may help.](https://github.com/elastic/azure-marketplace-examples/tree/master/azure_monitor_logstash)

**Comment by 0GiS0** [comment]
Thanks @russcam !

What I could see was I didn't have some parameters in the Azure Monitoring Module because [the documentation](https://www.elastic.co/guide/en/logstash/6.7/azure-module.html) doesn't say anything about them. (var.elasticsearch.username/password and  var.kibana.username/password)

I also wrote [a post about the configuration](https://www.returngis.net/2019/10/exportar-los-logs-de-microsoft-azure-a-elasticsearch/) to help others :)

Thank you so much for your help!
