### ISSUE TITLE
Unable to deploy Elasticsearch template

### ISSUE THREAD

**Issue by mruf** [elastic/azure-marketplace#261]
I'm trying to deploy the Elasticsearch template on Azure through the Azure Portal. It fails with the following error message when creating the VMs:
`
"statusCode": "Conflict",
"statusMessage": {
	"status": "Failed",
	"error": {
		"code": "ResourceDeploymentFailure",
		"message": "The resource operation completed with terminal provisioning state 'Failed'.",
		"details": [
			{
				"code": "DeploymentFailed",
				"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
				"details": [
					{
						"code": "Conflict",
						"message": "{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"DeploymentFailed\\\",\\r\\n \\\"message\\\": \\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"BadRequest\\\",\\r\\n \\\"message\\\": \\\"{\\\\r\\\\n \\\\\\\"error\\\\\\\": {\\\\r\\\\n \\\\\\\"code\\\\\\\": \\\\\\\"InvalidContentLink\\\\\\\",\\\\r\\\\n \\\\\\\"message\\\\\\\": \\\\\\\"Unable to download deployment content from 'https://catalogartifact.azureedge.net/publicartifacts/elastic.elasticsearch-ada67ba1-cf04-42a0-b3e9-d6a2bf310a3c-elasticsearch/Artifacts//partials/vm.json'. The tracking Id is '69f90610-d8ff-4378-accf-3c9a41de5af6'. Please see https://aka.ms/arm-deploy for usage details.\\\\\\\"\\\\r\\\\n }\\\\r\\\\n}\\\"\\r\\n },\\r\\n {\\r\\n \\\"code\\\": \\\"BadRequest\\\",\\r\\n \\\"message\\\": \\\"{\\\\r\\\\n \\\\\\\"error\\\\\\\": {\\\\r\\\\n \\\\\\\"code\\\\\\\": \\\\\\\"InvalidContentLink\\\\\\\",\\\\r\\\\n \\\\\\\"message\\\\\\\": \\\\\\\"Unable to download deployment content from 'https://catalogartifact.azureedge.net/publicartifacts/elastic.elasticsearch-ada67ba1-cf04-42a0-b3e9-d6a2bf310a3c-elasticsearch/Artifacts//partials/vm.json'. The tracking Id is '8de79b60-eb34-4b73-9d00-965cf35a790d'. Please see https://aka.ms/arm-deploy for usage details.\\\\\\\"\\\\r\\\\n }\\\\r\\\\n}\\\"\\r\\n },\\r\\n {\\r\\n \\\"code\\\": \\\"BadRequest\\\",\\r\\n \\\"message\\\": \\\"{\\\\r\\\\n \\\\\\\"error\\\\\\\": {\\\\r\\\\n \\\\\\\"code\\\\\\\": \\\\\\\"InvalidContentLink\\\\\\\",\\\\r\\\\n \\\\\\\"message\\\\\\\": \\\\\\\"Unable to download deployment content from 'https://catalogartifact.azureedge.net/publicartifacts/elastic.elasticsearch-ada67ba1-cf04-42a0-b3e9-d6a2bf310a3c-elasticsearch/Artifacts//partials/vm.json'. The tracking Id is 'd81ab138-2788-4d49-bb0c-16a3dc63d965'. Please see https://aka.ms/arm-deploy for usage details.\\\\\\\"\\\\r\\\\n }\\\\r\\\\n}\\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"
					}
				]
			}
		]
	}
},
`

**Comment by alcesleo** [comment]
I'm getting the exact same error.

**Comment by russcam** [comment]
Thanks for reporting @mruf. This looks like an Azure Marketplace issue:

- The url `https://catalogartifact.azureedge.net/publicartifacts/elastic.elasticsearch-ada67ba1-cf04-42a0-b3e9-d6a2bf310a3c-elasticsearch/Artifacts//partials/vm.json` is one that the Marketplace template upload process generates. It looks like the double `//` before partials is the issue here.

I'll look at updating the Marketplace template. In the meantime, you'd be able to [deploy from the command line (Azure CLI or PowerShell)](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-getting-started.html) and target a specific release tag in this GitHub repository. For example,

Azure CLI 2.0

```sh
template_base_uri=https://raw.githubusercontent.com/elastic/azure-marketplace
template_version=6.6.0

az group deployment create \
  --resource-group "<name>" \
  --template-uri $template_base_uri/$template_version/src/mainTemplate.json \
  --parameters artifactsBaseUrl=$template_base_uri/$template_version/src \
               esVersion=6.6.0 esClusterName=elasticsearch \
               vmDataDiskCount=1 dataNodesAreMasterEligible=Yes \
               adminUsername=russ adminPassword=Password1234 \
               securityBootstrapPassword=bootstrapPassword123 \
               securityAdminPassword=adminPassword123 \
               securityReadPassword=readPassword123 \
               securityKibanaPassword=kibanaPassword123 \
               securityLogstashPassword=logstashPassword123 \
               securityBeatsPassword=beatsPassword123
``` 

or Azure PowerShell

```powershell
$templateBaseUri = "https://raw.githubusercontent.com/elastic/azure-marketplace"
$templateVersion = "6.6.0"

$parameters = @{
  "artifactsBaseUrl" = "$templateBaseUri/$templateVersion/src"
  "esVersion" = "6.6.0"
  "esClusterName" = "elasticsearch"
  "vmDataDiskCount" = 1
  "dataNodesAreMasterEligible" = "Yes"
  "adminUsername" = "russ"
  "adminPassword" = "Password1234"
  "securityBootstrapPassword" = "bootstrapPassword123"
  "securityAdminPassword" = "adminPassword123"
  "securityReadPassword" = "readPassword123"
  "securityKibanaPassword" = "kibanaPassword123"
  "securityLogstashPassword" = "logstashPassword123"
  "securityBeatsPassword" = "beatsPassword123"
}

$deployment = New-AzureRmResourceGroupDeployment -ResourceGroupName "<name>" `
  -TemplateUri "$templateBaseUri/$templateVersion/src/mainTemplate.json" `
  -TemplateParameterObject $parameters
```

**Comment by russcam** [comment]
I've opened #263 to address.

**Comment by russcam** [comment]
6.6.1 is now live in the Marketplace. Thank you for your patience 👍
