### ISSUE TITLE
Missing Azure Lsv2 VM Sizes

### ISSUE THREAD

**Issue by okke-formsma** [elastic/azure-marketplace#265]
After support for the Fsv2 and L-series, please also add support for the Ls_v2 series of VMs. They seem to be a great match for elastic clusters with their super high IO throughput.

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-storage#lsv2-series

https://github.com/elastic/azure-marketplace/issues/221
https://github.com/elastic/azure-marketplace/issues/107

The great thing about these machines is the large ephemeral drive(s) /dev/nvmeX which could be used in a high-performance, low-availability cluster.

**Comment by russcam** [comment]
I've opened #271 to add support for Lsv2 VMs. This does not include using local NVMe storage yet. This should be tackled in a subsequent PR.

**Comment by russcam** [comment]
I've added #272 for using NVMe storage.

**Comment by russcam** [comment]
This change is now in master; once the template is approved for production, I'll tag the 6.7.0 release
