### ISSUE TITLE
Update to 7.0

### ISSUE THREAD

**Issue by JoaquimFreitas** [elastic/azure-marketplace#274]
Hi,

Will the Marketplace Solution and ARM Template be updated to the latest Elasticsearch 7.0?
If yes, when can we expect that update?

Thanks in advance.

**Comment by russcam** [comment]
Hi @JoaquimFreitas, thanks for opening this. I don't have an ETA for when this will be completed, but we're expecting to start on it shortly.

**Comment by russcam** [comment]
I've opened #275
