### ISSUE TITLE
Clarify subnet constraints for the UI app

### ISSUE THREAD

**Issue by kostasb** [elastic/azure-marketplace#283]
__Can we add clarifications in the docs about the subnet size requirements for the UI app:__

The [Azure Marketplace UI solution](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-marketplace-getting-started.html) constrains the available subnets under the Virtual Network configuration section to those that have a prefix size of /25 i.e. 128 addresses or more.

__Also, would be good to point out the known workarounds:__

This is only a Marketplace UI constraint and not an ARM template constraint, so you can deploy a cluster using the [template from our GitHub repository](https://github.com/elastic/azure-marketplace) and select the existing vnet and subnet that you would like to use, using the [networking input parameters](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-networking.html).

For consistency purposes in repeatable deployments it is recommended to target a specific GitHub branch, instead of the master branch which is constantly evolving.

**Comment by russcam** [comment]
I've opened #284 to address

**Comment by kostasb** [comment]
Perfect, thanks!

**Comment by russcam** [comment]
Closing this as #284 has been merged and will be in docs shortly
