### ISSUE TITLE
add template deployment support to include native and Saml auth

### ISSUE THREAD

**Issue by smarshal-Quest** [elastic/azure-marketplace#290]
I am using tag 7.1.1 and my deployment is configured to use Azure AD SAML
This configuration does work but if i add  native auth realm to 

esAdditionalYaml . it skips the setup during deployment.
[24062019-14:01:47] [configure_elasticsearch_yaml] Skipping line 'xpack.security.authc.realms.native.native1.order: 0'

We require to use of native account for logstash to ship logs to elasticsearch, is there a way to have this configurable when deploying from ARM template ?

**Comment by russcam** [comment]
Hi @smarshal-Quest. 

> esAdditionalYaml . it skips the setup during deployment.
[24062019-14:01:47] [configure_elasticsearch_yaml] Skipping line 'xpack.security.authc.realms.native.native1.order: 0'

It is correct that the template deployment prevents you from applying this setting, but it's a bug that the native realm is not also configured when the SAML realm is configured. The native realm is configured by default when no other realms are configured. 

The `elastic` superuser account will be able to connect to the cluster, although you'll likely want an account with more limited authorization, like `logstash_system`.  We'll fix this in the next release which should be shortly. Tthe workaround for now would be to ssh into each Elasticsearch node in turn, add the native realm configuration to `/etc/elasticsearch/elasticsearch.yml`, then restart the elasticsearch process

```sh
sudo systemctl restart elasticsearch.service
```

to pick up the change. Be sure to wait for each Elasticsearch node in turn, and have sufficient replica shards to continue normal cluster operation.

**Comment by russcam** [comment]
I've opened #291 to address

**Comment by russcam** [comment]
#291 is now merged and will be in the next tagged release. Closing this
