### ISSUE TITLE
The template variable 'nodesPerStorageAccount' is not valid

### ISSUE THREAD

**Issue by crunchie84** [elastic/azure-marketplace#3]
```Error submitting the deployment request. Additional details from the underlying API that might be helpful: Deployment template validation failed: 'The template variable 'nodesPerStorageAccount' is not valid: Template language expression property 'Standard_A1' doesn't exist, available properties are 'Standard_D1, Standard_D2, Standard_D3, Standard_D4, Standard_DS1, Standard_DS2, Standard_DS3, Standard_DS4, Standard_DS13, Standard_A2, Standard_A3, Standard_A4, Standard_A7'..'.```

parameters provided in azure portal:
- esversion 2.1.0
- loadbalancertype: internal
- esclustername: elasticsearch
- loadbalancertype: internal
- esplugins: no
- kibana: no
- jumpbox: no
- vmsizedatanodes: Standard_A1
- vmdatanodecount: 3
- datanodesaremastereligible: yes
- vmsizemasternodes: Standard_A1
- vmclientnodecount: 0
- vmsizeclientnodes: Standard_A1
- adminusername: provided
- authenticationtype: password
- adminpassword provided
- sshpublickey: <empty>
- shieldadminpassword: <empty>
- shieldreadpassword: <empty>
- shieldkibanapassword: <empty>
- Location: ResourceGroup
- VirtualNetworkName: esvnet

**Comment by crunchie84** [comment]
The dropdowns in the parameter selection suggest that i am able to choose `Standard_A1` but the error states otherwise :cry:

**Comment by Mpdreamz** [comment]
Thanks mark!

The data nodes are currently still limited to the vm sizes mapped here:

https://github.com/elastic/azure-marketplace/blob/dee5dc4185ddff6b1d5881de033038aca499a9b8/src/mainTemplate.json#L429

We need to update that mapping with the allowedValues here:

https://github.com/elastic/azure-marketplace/blob/master/src/allowedValues.json#L7

And the build should throw an error if these two do not line up correctly in the future again.

**Comment by Mpdreamz** [comment]
These two commits add sku validation to the build and adds the missing vm size sku

https://github.com/elastic/azure-marketplace/commit/ca0778df7bea1570c09c7ebf16431acc2b720f21

https://github.com/elastic/azure-marketplace/commit/6c6e7b5e216f6b5403dbc22de982d563c04fe0c1
