### ISSUE TITLE
Document node expansion limitations when deployed through Azure Storefront

### ISSUE THREAD

**Issue by adoerrES** [elastic/azure-marketplace#300]
In previous [internal discussions](https://github.com/elastic/support-dev-help/issues/5601#issuecomment-468144242) with the template development team, it was confirmed that Elastic Azure template deployments created through the Azure Marketplace UI do not support adding nodes at a later time.

This means that a Storefront deployment made to production will not be able to add nodes later if more capacity is required.  Instead, a new deployment will have to be made with the desired node count, and data will have to be copied between clusters, which is significant operational overhead (especially if one runs into heap memory pressure in a production instance).

The Github-based deployment *does* support [scaling up nodes](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-elasticsearch.html#azure-arm-template-scaling-nodes), and should be the method used to deploy.  

We should more clearly point out scaling limitations of the Storefront deployment, that it is only meant to get a quick development instance running for testing purposes, and that the Github-based deployment should be used instead.  

Perhaps a disclaimer at the beginning of the [Getting Started](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-getting-started.html) page?

**Comment by russcam** [comment]
> In previous internal discussions with the template development team, it was confirmed that Elastic Azure template deployments created through the Azure Marketplace UI do not support adding nodes at a later time.

To be clear, it's not that deployments through the Azure Marketplace UI do not support adding nodes at a later time, it's that the UI is not really designed for this, and the steps to take to achieve it can be convoluted. The Marketplace offering only has the latest template version available, so if a user has deployed with an older template version, redeploying through the Marketplace UI would use the newer template version which may result in incompatible node configurations being deployed and the cluster not forming.

I've opened #353 to address.
