### ISSUE TITLE
when will 7.4.0 be released?

### ISSUE THREAD

**Issue by gesada** [elastic/azure-marketplace#311]
While using the template, it appears that only latest support version is 7.3.1- see error below 

Would we know when 7.4.0 is going to be support?

Thanks,
George 

10:41:57  * azurerm_template_deployment.elastic-iaas: Error creating deployment: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplate" Message="Deployment template validation failed: 'The provided value '7.4.0' for the template parameter 'esVersion' at line '1' and column '7405' is not valid. The parameter value is not part of the allowed value(s): '5.4.3,5.5.3,5.6.12,6.0.1,6.1.3,6.2.4,6.3.2,6.4.1,6.4.2'.'." AdditionalInfo=[{"info":{"lineNumber":1,"positionNumber":7405,"snippet":""},"type":"TemplateViolation"}]

**Comment by russcam** [comment]
I've opened https://github.com/elastic/azure-marketplace/pull/313
