### ISSUE TITLE
Upgrade cluster version

### ISSUE THREAD

**Issue by KenticoMartinS** [elastic/azure-marketplace#317]
Hi,
I wanna ask if there is a possibility to upgrade ES cluster to a new version. For example, I created ES cluster in version 7.2.1 and now I want to upgrade to 7.3.1.

I tried to change **esVersion** parameter for ARM template, but nothing happened. Should this work? Or is there a way how to upgrade version?

NOTE: We have Terraform configuration that uses ES ARM template to create a cluster. We want update **esVersion** in Terraform (7.2.1 -> 7.3.1) and upgrade the whole cluster (ES, Kibana, Logstash) to the new version.

**Comment by russcam** [comment]
You can upgrade a cluster to a new version, but **this is not something that the ARM template or Azure Marketplace offering supports**. For upgrades at the click of a button, you may want to look at [Elasticsearch Service on Azure](https://www.elastic.co/products/elasticsearch/service), which supports this. It'll be rolling out to more Azure regions in the future.

Once a cluster is deployed using the ARM template, the [upgrade process for the cluster](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/setup-upgrade.html) is the same as if Elasticsearch. Logstash and Kibana had been deployed onto Ubuntu VMs running anywhere. Going from 7.2.1 to 7.3.1, you would be able to [perform a rolling upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/rolling-upgrades.html), using the Debian package. You may want to consider upgrading to 7.4.1 at this stage.

Hope that helps.

**Comment by KenticoMartinS** [comment]
Hi @russcam,
thanks for the explanation. For the Elasticsearch Service on Azure, is there any list and roadmap of the future supported regions? 

Furthermore, is there any Rest API for Elastic Cloud (I wasn't able to find any)? Is it possible, to create ElasticSearch cluster on Elastic Cloud using scripts or do we have to manually create it through Elastic Cloud UI?
