### ISSUE TITLE
Transport and HTTP SSL not configured on Data Nodes

### ISSUE THREAD

**Issue by ridensnow23** [elastic/azure-marketplace#318]
I created a deployment for 5 data nodes and 2 coordinator nodes.  esHttpCaCertBlob and esTransportCaCertBlob were populated in the template to enable SSL for transport and HTTP traffic.  On the coordinating nodes, I can see that this was successfully enabled.  On the data nodes, however, the .p12 files were created in /etc/elasticsearch/ssl, but the following config is missing from elasticsearch.yml:

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: /etc/elasticsearch/ssl/elasticsearch-http.p12
xpack.security.http.ssl.truststore.path: /etc/elasticsearch/ssl/elasticsearch-http.p12
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.path: /etc/elasticsearch/ssl/elasticsearch-transport.p12
xpack.security.transport.ssl.truststore.path: /etc/elasticsearch/ssl/elasticsearch-transport.p12

This config does exist for the coordinating nodes.

**Comment by russcam** [comment]
Please can you provide 

1. the `arm-install.log` output for **one of the data nodes**? This log can be found in [`/var/log/arm-install.log`](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-troubleshooting-azure-logs.html#azure-arm-template-troubleshooting-azure-logs)
2. the parameters used for the deployment

**Comment by russcam** [comment]
@ridensnow23 Are you able to provide the above details, so that we can investigate?

**Comment by russcam** [comment]
I've added the deployment of a coordinating node to the test `1d-0m-0c-ext-tls-klp.json` in the 7.5.0 branch and deployed it with

```sh
$ git checkout feature/7.5.0
$ npm run release -- --test 1d\-0m\-0c\-ext\-tls\-klp.* --nodestroy
```

The `--nodestroy` flag keeps the deployment around after the tests run. I've then ssh'ed into the client and data nodes to check the configuration

```sh
$ ssh russ@<kibana public ip>
$ ssh data-0
$ sudo cat /etc/elasticsearch/elasticsearch.yml
cluster.name: "my-azure-cluster"
node.name: "data-0"
path.logs: /var/log/elasticsearch
path.data: /datadisks/disk1/elasticsearch/data
discovery.seed_hosts: ["data-0"]
cluster.initial_master_nodes: ["data-0"]
node.master: true
node.data: true
network.host: [_site_, _local_]
node.max_local_storage_nodes: 1
node.attr.fault_domain: 0
node.attr.update_domain: 0
cluster.routing.allocation.awareness.attributes: fault_domain,update_domain
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
bootstrap.memory_lock: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: /etc/elasticsearch/ssl/elasticsearch-http.p12
xpack.security.http.ssl.truststore.path: /etc/elasticsearch/ssl/elasticsearch-http.p12
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.path: /etc/elasticsearch/ssl/elasticsearch-transport.p12
xpack.security.transport.ssl.truststore.path: /etc/elasticsearch/ssl/elasticsearch-transport.p12

$ ssh client-0
$ sudo cat /etc/elasticsearch/elasticsearch.yml
cluster.name: "my-azure-cluster"
node.name: "client-0"
path.logs: /var/log/elasticsearch
path.data: /var/lib/elasticsearch
discovery.seed_hosts: ["data-0"]
cluster.initial_master_nodes: ["data-0"]
node.master: false
node.data: false
network.host: [_site_, _local_]
node.max_local_storage_nodes: 1
node.attr.fault_domain: 0
node.attr.update_domain: 0
cluster.routing.allocation.awareness.attributes: fault_domain,update_domain
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
bootstrap.memory_lock: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: /etc/elasticsearch/ssl/elasticsearch-http.p12
xpack.security.http.ssl.truststore.path: /etc/elasticsearch/ssl/elasticsearch-http.p12
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.path: /etc/elasticsearch/ssl/elasticsearch-transport.p12
xpack.security.transport.ssl.truststore.path: /etc/elasticsearch/ssl/elasticsearch-transport.p12
```
I can't replicate the issue; the elasticsearch.yml configuration is the same on both data and coordinating nodes.

I'm going to close this issue, but if you can provide a reproduction, please feel free to reopen to discuss 👍
