### ISSUE TITLE
Error about vmSizeClientNodes

### ISSUE THREAD

**Issue by aeslinger0** [elastic/azure-marketplace#319]
I'm getting the following error trying to add elasticsearch to Azure. I left "Number of client nodes" at zero because the tooltip said it was optional. Is this not the case? Is there a way to work around this error?

> Deployment template validation failed: 'The provided value 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Common.Entities.TemplateGenericProperty`1[Newtonsoft.Json.Linq.JToken]' for the template parameter '**vmSizeClientNodes**' at line '972' and column '24' is not valid. The parameter value is not part of the allowed value(s): 'Standard_A0,Standard_A1,Standard_A2,Standard_A3,Standard_A4,Standard_A5,Standard_A6,Standard_A7,Standard_A8,Standard_A9,Standard_A10,Standard_A11,Standard_D1,Standard_D2,Standard_D3,Standard_D4,Standard_D11,Standard_D12,Standard_D13,Standard_D14,Standard_D1_v2,Standard_D2_v2,Standard_D3_v2,Standard_D4_v2,Standard_D5_v2,Standard_D11_v2,Standard_D12_v2,Standard_D13_v2,Standard_D14_v2,Standard_D15_v2,Standard_D2_v3,Standard_D4_v3,Standard_D8_v3,Standard_D16_v3,Standard_D32_v3,Standard_D64_v3,Standard_DS1,Standard_DS2,Standard_DS3,Standard_DS4,Standard_DS11,Standard_DS12,Standard_DS13,Standard_DS14,Standard_DS1_v2,Standard_DS2_v2,Standard_DS3_v2,Standard_DS4_v2,Standard_DS5_v2,Standard_DS11_v2,Standard_DS12_v2,Standard_DS13_v2,Standard_DS14_v2,Standard_DS15_v2,Standard_D2s_v3,Standard_D4s_v3,Standard_D8s_v3,Standard_D16s_v3,Standard_D32s_v3,Standard_D64s_v3,Standard_E2_v3,Standard_E4_v3,Standard_E8_v3,Standard_E16_v3,Standard_E32_v3,Standard_E64_v3,Standard_E64i_v3,Standard_E2s_v3,Standard_E4s_v3,Standard_E8s_v3,Standard_E16s_v3,Standard_E32s_v3,Standard_E64s_v3,Standard_E64is_v3,Standard_F1,Standard_F2,Standard_F4,Standard_F8,Standard_F16,Standard_F1s,Standard_F2s,Standard_F4s,Standard_F8s,Standard_F16s,Standard_F2s_v2,Standard_F4s_v2,Standard_F8s_v2,Standard_F16s_v2,Standard_F32s_v2,Standard_F64s_v2,Standard_F72s_v2,Standard_G1,Standard_G2,Standard_G3,Standard_G4,Standard_G5,Standard_GS1,Standard_GS2,Standard_GS3,Standard_GS4,Standard_GS5,Standard_L4s,Standard_L8s,Standard_L16s,Standard_L32s,Standard_L8s_v2,Standard_L16s_v2,Standard_L32s_v2,Standard_L64s_v2,Standard_L80s_v2,Standard_M8ms,Standard_M16ms,Standard_M32ts,Standard_M32ls,Standard_M32ms,Standard_M64s,Standard_M64ls,Standard_M64ms,Standard_M128s,Standard_M128ms,Standard_M64,Standard_M64m,Standard_M128,Standard_M128m'.'.

**Comment by aeslinger0** [comment]
I found I can work around it by setting the number of client nodes to 1, selecting a valid size, then setting it back to zero. This makes me believe it is related to #315 in that both cases are where the validations are not conditional based on their parent field values.

**Comment by russcam** [comment]
Thanks for reporting @aeslinger0, this does look to be the same issue as #315

**Comment by russcam** [comment]
Closing this issue. This was a bug introduced into the Azure portal, confirmed by folks at Microsoft, which has now been addressed.
