### ISSUE TITLE
remove support for kibana4 user

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/azure-marketplace#32]
The default kibana4 role is gone as per 2.3

> 2016/05/19 11:53:35 Warning: The following roles [kibana4] are unknown. Make sure to add them to the [/etc/elasticsearch/shield/roles.yml] file. Nonetheless the user will still be associated with all specified roles

**Comment by russcam** [comment]
I've added a kibana4 role configuration to the roles.yml file for now in https://github.com/elastic/azure-marketplace/commit/bc6f9e92c81428415517276a1396eee5300125bd, based on the privileges of the previous kibana4 role
