### ISSUE TITLE
VMSS Extension issue "The property 'CachedDataSyncPort' cannot be found on this object."

### ISSUE THREAD

**Issue by ForrestIsARealGoodman** [elastic/azure-marketplace#322]
Hi Experts,

When I tried to executed terraform script to create a vmss resource, code similar to:
`resource "azurerm_virtual_machine_scale_set" "broker" {
  name                         = "${local.prefix}-broker"
...
extension {
    name                 = "ConfigureBroker"
    publisher            = "Microsoft.Powershell"
    type                 = "DSC"
    type_handler_version = "2.73"

    settings = <<SETTINGS
    {
        "ModulesUrl": "${***.url}",
        "SasToken": "${***.sas}",
        "ConfigurationFunction": "VMConfiguration.ps1\\Broker",
        "Properties":{  
          "is_staging":"${var.is_staging}",
          "service_name":"${var.service_name}",
          "client_id":"${var.vault_client_id}",
          "certificate_thumbprint":"${trimspace(data.local_file.kv-thumbprint.content)}",
          "vault_name":"${azurerm_key_vault.wem-keyvault.name}"
        }
    }
    SETTINGS
  }
`
it thrown error as below:
`
Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'ConfigureBroker'. Error message: \"DSC Configuration 'Broker' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: The property 'CachedDataSyncPort' cannot be found on this object. Verify that the property exists and can be set.  The SendConfigurationApply function did not succeed.\"."

  on broker.tf line 35, in resource "azurerm_virtual_machine_scale_set" "wem-broker":
  35: resource "azurerm_virtual_machine_scale_set" "wem-broker" {
`
Not sure what the  property 'CachedDataSyncPort' is, while the dsc powershell could works in the local environment.
[Expected]
It should works fine.

**Comment by russcam** [comment]
Hi @ForrestIsARealGoodman,

I think you've posted this in the wrong GitHub repository; This repository is for Elastic's Azure Marketplace, an Azure Resource Manager template for deploying the Elastic Stack to Azure. Terraform is not used by this template. I can't determine based on the information presented where it might be best to direct you to open an issue, but I am going to close this issue here.

**Comment by ForrestIsARealGoodman** [comment]
Sorry for posting it in wrong site.
Thanks anyway.
