### ISSUE TITLE
A way to disable Basic Security with ES version >= 7.1.0?

### ISSUE THREAD

**Issue by quimrodri** [elastic/azure-marketplace#331]
We are installing an internal ES cluster. After playing with the options and reviewing the elasticsearch-install.sh script we don't see any option to disable Basic Security if we install ES version >= 7.1.0 (7.6.0 in our case)
Am I missing something?

_TL;DR_
We would like to do it because:
-  We suppose that the certificates that this line will generate:
https://github.com/elastic/azure-marketplace/blob/d1098632bd22e54d5966c67033d4b03e6547c725/src/scripts/elasticsearch-install.sh#L808
will have a validity of 3 years (as the default value of --days parameter is 1095). And this will be the case even-though we generate a 5, 10 or 15 years valid CA certificate.
- We assume that if we don't update this certificates, after 3 years, the cluster will stop working because of the expired certificates

As we want to prevent this from happening we were wondering if disabling SSL between nodes was an option but then we found this issue: https://discuss.elastic.co/t/setting-xpack-security-enabled-true/182791/5  and as the answer already states, the only option we have is to disable Basic Security altogether.

BTW: It was not clear for us that esTransportCaCertBlob is mandatory if ES version >= 7.1.0 from the  documentation and we didn't provided it (hopping that this will disable SSL for Transport layer) and after restarting the data nodes the whole cluster failed to boot due to the error stated before

**Comment by russcam** [comment]
Hey @quimrodri 

security cannot be disabled (`xpack.security.enabled: false`) for Elasticsearch 6.8+ (and less than 7.x) , and for 7.1+, as part of installation. This is intentional so that a [deployment of Elasticsearch on Azure has basic authentication](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-security.html#authentication-and-authorization) in place.

> will have a validity of 3 years (as the default value of --days parameter is 1095). And this will be the case even-though we generate a 5, 10 or 15 years valid CA certificate.
>
> We assume that if we don't update this certificates, after 3 years, the cluster will stop working because of the expired certificates
>
> As we want to prevent this from happening we were wondering if disabling SSL between nodes was an option but then we found this issue: https://discuss.elastic.co/t/setting-xpack-security-enabled-true/182791/5 and as the answer already states, the only option we have is to disable Basic Security altogether.

I **strongly advise** that you run with TLS on both the Transport and HTTP layers. It's normal for certificates to expire and to issue new certificates and configure them when they do. Elasticsearch monitors files related to TLS-related node settings, and will reload them when changed, so before certificates expire, if you replace the certificates with new ones (issued by same CA, with same CN and SAN entries), the cluster will continue to operate without downtime.

**Comment by quimrodri** [comment]
Hi @russcam thanks for you fast response :)

I understand your recommendations. It’s something we wanted to do deliberately. But I’ll challenge this decision again.

We’ll love to not have any manual intervention when managing the cluster (as we have been doing for previous versions of the template) and be able to do all the operations from Octopus and the deployment scripts as we do now. We’ll figure out how to add a “generate new certificates if expired” to the deployment steps.

I have a question: is the assumption of the validity duration of the certificates (3 years) correct?

And, as I understand, every time that we scale-out the cluster using the ARM template the new nodes will have a new generated certificate so, new expiration dates, and different ones from already created nodes isn’t it?

Thanks!

**Comment by russcam** [comment]
> I have a question: is the assumption of the validity duration of the certificates (3 years) correct?

Yes,  the [default validity used by the `elasticsearch-certutil` tool is 3 * 365 days](https://github.com/elastic/elasticsearch/blob/c1a6d5d9ffead45efd3238432d2cca3add54fa9f/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java#L102)

> And, as I understand, every time that we scale-out the cluster using the ARM template the new nodes will have a new generated certificate so, new expiration dates, and different ones from already created nodes isn’t it?

When [scaling up](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-elasticsearch.html#azure-arm-template-scaling-nodes), new nodes will:

- have certificates generated using the provided CA certificate for the Elasticsearch Transport layer
- use the certificate provided, or generate a new certificate using the provided CA certificate for the Elasticsearch HTTP layer

With self-managing Elasticsearch, whether it be using the ARM template, or one of the packages/archives like RPM, zip, Debian, etc. you'll need to manage certificates. I think it's fair to say that this is the case for any self-managed system that uses Transport Layer Security.

**Comment by quimrodri** [comment]
Thanks for you answer.
