### ISSUE TITLE
Incorrect elasticsearch.yml file after deploying more than once (ES cluster goes down)

### ISSUE THREAD

**Issue by quimrodri** [elastic/azure-marketplace#334]
We have found that if we deploy multiple times the ARM template it could end up with the cluster down because a misconfiguration in the /etc/elastictcsearch.yml file.

It seems that the script elasticsearh-install.sh is not idempotent after configuring https TLS or Transport TLS (mandatory in latest versions). 

Here: https://github.com/elastic/azure-marketplace/blob/dd47b8e72b93f204e00701f666a80096b1771c41/src/scripts/elasticsearch-install.sh#L646
and here: https://github.com/elastic/azure-marketplace/blob/dd47b8e72b93f204e00701f666a80096b1771c41/src/scripts/elasticsearch-install.sh#L781
it checks that the certificates files already exists to decide if the functions configure_transport_tls() and configure_http_tls() continues or it returns back.

But, the second time you run this script, these files will already exist and the function will return without adding the configuration needed for Transport TLS and HTTP TLS in the elasticsearch.yml file (it gets written down later in the same function).
As it will switch to the new configuration without this needed parts the cluster will go down after reloading the config  ([this check](https://github.com/elastic/azure-marketplace/blob/dd47b8e72b93f204e00701f666a80096b1771c41/src/scripts/elasticsearch-install.sh#L1211)  will always be true and will always reload it).

This will happen whenever the customscript will run again. We have observed that this happen any time we change a paramatere of the ARM templates (for example, to add a custom YML configuration, or scale-up the machine, etc..).

**Comment by russcam** [comment]
Thanks for opening @quimrodri, this is a bug

**Comment by russcam** [comment]
I've opened https://github.com/elastic/azure-marketplace/pull/335 to address.

**Note:** When all parameters are _exactly_ the same as a previous deployment in a resource group, it appears that the Azure infrastructure does not run the deployment scripts when performing a new deployment into that resource group. This is based on the fact that the `/var/log/arm-install.log` does not contain any log entries for the re-deployment, when it would contain some if the deployment script had ran.

**Comment by quimrodri** [comment]
Thanks @russcam ! 😄 

Yes, that's exactly what we have observed, when all parameters are exactly the same, as the script is not run, it doesn't changes the configuration. But in Microsoft documentation they state that the script should always be idempotent because it could be run again "anytime" (whatever this means).

BTW I've seen that you are labeling the bugfix as 7.7.0. Does it means that the 7.7.0 is imminent? Are we talking about days? weeks? I would like to know it because where are deploying a new cluster so we could just wait a little bit more to deploy it with the 7.7.0 version or we just proceed and deploy it with 7.6.2 (to later on upgrade the ARM template with this fix).

**Comment by russcam** [comment]
I thought I'd document the observation in behaviour, as I'm fairly sure the VM scripts used to run in this scenario in the past, with the old waagent, so the scripts need to be idempotent.

> BTW I've seen that you are labeling the bugfix as 7.7.0. Does it means that the 7.7.0 is imminent? Are we talking about days? weeks?

This fix will go into the next release, which will be 7.7.0. I can't give you an exact timeline for when this will be, but [we do try to release often](https://www.elastic.co/downloads/past-releases#elasticsearch).
