### ISSUE TITLE
Unable to deploy official self-managed Elasticsearch template with Kibana

### ISSUE THREAD

**Issue by martincigorraga** [elastic/azure-marketplace#343]
Hi,

I'm having a validation error when trying to enable Kibana in the deployment template:

> ERRORSThe template deployment 'elastic.elasticsearch-20200518112808' is not valid according to the validation procedure. The tracking id is 'a458e340-f925-44e7-a910-3d6c8583a453'. See inner errors for details.

Relevant information that may help:

- I'm able to deploy all sorts of clusters whith Kibana disabled
- I double-checked Kibana's CSR and KEY files and they are good
- I generated the certificate and key for Kibana by following the official documentation: https://www.elastic.co/guide/en/kibana/current/configuring-tls.html (I'm using the official image  `elasticsearch:7.6.2`)

![k0](https://user-images.githubusercontent.com/58219321/82235605-4b947f80-9909-11ea-94d2-75d03754ab0c.png)

![k1](https://user-images.githubusercontent.com/58219321/82235621-5222f700-9909-11ea-9a37-cd3ce9619065.png)

![k2](https://user-images.githubusercontent.com/58219321/82235625-54855100-9909-11ea-8192-177d31235076.png)

Any idea where could lie the error? Is there a way I can access the template for troubleshooting?

Thanks!

**Comment by russcam** [comment]
> ERRORSThe template deployment 'elastic.elasticsearch-20200518112808' is not valid according to the validation procedure. The tracking id is 'a458e340-f925-44e7-a910-3d6c8583a453'. See inner errors for details.

What does the inner error say? The validation procedure is part of the Azure infrastructure, so it may be related to something like [CPU quota limits](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits) available in the subscription.

**Comment by martincigorraga** [comment]
Hi Russ, thanks for your reply. What do you mean why inner error message? This is the only feedback I got :(
In any case, it makes sense your guess since I know we are almost at the limit regarding the CPU quota in our subscription.
If there's any way to get more information about this issue, I can happily try to trigger this error again; if there's not, I would then close the issue, let me know.

**Comment by russcam** [comment]
Have a look at the Microsoft docs on [common deployment errors](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/common-deployment-errors) and [where to find the error](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-tutorial-troubleshoot#troubleshoot-the-validation-error); If I recall correctly, there should be a link to click on in the Azure portal on a template validation error that opens a blade with further details

**Comment by martincigorraga** [comment]
@russcam : could it be the feature you mention could be somewhat new, and deployed in waves? When I first reported this issued, trust me that the functionality wasn't there, so you would end up with a cryptic non-sense error message.

Earlier this afternoon I went to deploy a new cluster (using your very same template) and this time when I got an error, I could see that blade you talk about, with all the information you need to understand why the template was failing.

In any case, thanks a lot for providing that quite useful template (I'm working on a Terraform + Ansible scripts tho to better suit my needs).

All the best!

**Comment by russcam** [comment]
The validation error blade has existed for as long as the template has, ~5 years. What does happen from time to time however is that the portal UI is updated, so it could have just been a few runs where for some reason the blade didn't show. Glad to hear it did eventually appear!
