### ISSUE TITLE
Add ES version 7.6.0 to allowed values

### ISSUE THREAD

**Issue by mikisg85** [elastic/azure-marketplace#345]
Hi @russcam,

I am a work colleague of @quimrodri and we have found that the [change](https://github.com/elastic/azure-marketplace/pull/332/commits/84244d5461d961e02f2a132dbb1d8ee746846615) we did to update Elasticsearch 7.6.0 to latest patch version is now blocking us.

Basically, our situation right now is that we have two new ES clusters created a month ago aprox using this ARM template pointing to the release 7.6.0 and the clusters are running ES version 7.6.0. However, we found an important bug in the installation scripts that was preventing us to re-deploy the infrastructure without downtime (for example if we need to add a new node) and this was corrected [here](https://github.com/elastic/azure-marketplace/pull/335)

So, we would like to use the latest version of the ARM template (with bug fixes) but keeping the same ES version. Right now is not possible because we removed version 7.6.0 from allowedValues.json

Would it be possible to revert the change we did, or just add version 7.6.0 back as allowed value?

Thank you!

**Comment by russcam** [comment]
Hi @mikisg85, when a new major or minor version is added to the template, the older minor versions are typically updated to their latest patch release. Patch releases contain bug fixes to a minor version, which is some cases, like security issues, we **strongly** recommend upgrading to. For this reason, I would be against adding back older patch versions into a new template version.

**Comment by mikisg85** [comment]
Ok, thanks @russcam for the explanation. We will try to solve the issue upgrading the cluster to version 7.7
