### ISSUE TITLE
TLS issue connecting to Search from Azure Function

### ISSUE THREAD

**Issue by dwwhalen** [elastic/azure-marketplace#346]
We are running into an issue and thought I might get some help here.  I have deployed Elastic into Azure using the template and am able to establish encrypted connection between Kibana and the cluster with no issues.  I now want an Azure function to be able to load data to into Elastic, and we are running into issues with the TLS encryption.

To install Search, I have:
 - followed the directions to create a custom CA as described in https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls.html#node-certificates, step 1.  This creates a .p12 file (no password). 
- added that to the Azure Key Vault as a Secret and use it for the esTransportCaCertBlob and esHttpCaCertBlob params in the deploy.  I then successfully deploy in Azure using the ARM template.

The problem is with the Azure Function.  We have creates an App Service for the function.  To configure TSL I did the following:
- generated a cert and private key using step 2 of the link above
- uploaded it as a Private Key Certificate in the TLS/SSL settings for the function in Azure
- added a app-setting called WEBSITE_LOAD_CERTIFICATES and set the value to the thumbprint of the Private Key Certificate uploaded in the previous step
- updated the function to read the app-setting value from the environment variable and pull that certificate from the machines cert store

Unfortunately when the function attempts to connect we get an error “The SSL could not be established. The remote certificate is invalid according to the validation procedure."

Any guidance with this issue would be greatly appreciated.

**Comment by russcam** [comment]
Hi @dwwhalen, this might possibly be better asked on https://discuss.elastic.co/c/elasticsearch as more folks peruse the discussion forums, but I'll try to answer here.

From the description, it sounds like TLS has been configured for the [Transport layer](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-security.html#transport-layer) of the cluster, but not for the [HTTP layer](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-security.html#http-layer). The transport layer is used by nodes for inter-node communication, and the HTTP layer is used by Kibana, clients and applications that interact with Elasticsearch. A certificate can be supplied for the HTTP layer with `esHttpCertBlob`, which must be a base 64 encoded PKCS#12 archive containing the certificate and key. An optional passphrase for the archive can be passed with `esHttpCertPassword`. 

Reading further, it sounds like you might be wanting to use a client certificate to authenticate to the cluster inside the Azure function? If I've understood that correctly, [a PKI realm needs to be configured in Elasticsearch for this.](https://www.elastic.co/guide/en/elasticsearch/reference/current/pki-realm.html). [PKI authentication requires a minimum Gold subscription](https://www.elastic.co/subscriptions) _(search for PKI on that page)_.

**Comment by dwwhalen** [comment]
Thanks for the reply Russ.  I was not very clear in my original post.  Actually we do have TLS configured for the HTTP layer by using the esHttpCaCertBlob param.  This was generated as a custom CA.

I believe the problem with the Function is it does not like the cert because it does not trust the custom CA that was used to generate it.  So that's why the Function gets the error "the remote certificate is invalid according to the validation procedure".  We looked for a way to make Azure trust that custom CA but it looks like that is not supported.

Maybe instead of the custom CA being used in esHttpCaCertBlob, we should generate a cert using a trusted CA and supply it in the esHttpCertBlob param?  Will that same cert then used for the HTTP layer for each node?

**Comment by dwwhalen** [comment]
AND...if we use the esHttpCertBlob for the HTTP layer for all nodes, that cert will need to match the domain name of the nodes, correct?

**Comment by russcam** [comment]
> Maybe instead of the custom CA being used in esHttpCaCertBlob, we should generate a cert using a trusted CA and supply it in the esHttpCertBlob param? Will that same cert then used for the HTTP layer for each node?

> AND...if we use the esHttpCertBlob for the HTTP layer for all nodes, that cert will need to match the domain name of the nodes, correct? FYI we are using external load balancer.

If `esHttpCertBlob` is used, the same certificate will be used for the HTTP layer of all nodes. If you're connecting to Elasticsearch from Azure functions through the internal load balancer, then you'll likely want to have a SAN IP address entry in the generated certificate for the IP address of the internal load balancer. With this in place, you'd be able to verify that the certificate was issued by the CA expected and hostname verification will work. If you're connecting to Elasticsearch through the external load balancer, you'll likely want to have a SAN DNS entry in the generated certificate for a CNAME on a domain that you control that points to the public domain name of the external loadbalancer public IP address,  and connect through the CNAME.
