### ISSUE TITLE
Adding more nodes to an existing cluster build with Elastic Stack Azure Marketplace

### ISSUE THREAD

**Issue by jwcw** [elastic/azure-marketplace#347]
Hello,

I have an elasticsearch cluster that was built a couple of years ago with the templates, however the specific configurations/templates are long gone and the cluster's configuration has since changed.

What approaches are available for adding nodes to this cluster? Can I create a new deployment to add nodes in? Do I need to manually create new VMs and join them to the cluster?

Thank you.

**Comment by russcam** [comment]
Hi @jwcw,

A way to add nodes to the cluster that _should_ work irrespective of how the cluster was deployed (from Marketplace or from GitHub) is to create a new VM, deploy Elasticsearch on it, and add it to the cluster. 

An existing node in the cluster should have the scripts used to deploy Elasticsearch onto it in the `/var/lib/waagent/custom-script/download/0/` directory - it should be called `elasticsearch-install.sh`. In addition to the install script, this directory _should_ also have a log of `stdout` and `stderr` when  the deployment scripts ran, which, in addition to the [template's own log file `/var/log/arm-install.log`](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-troubleshooting-azure-logs.html) and a node's configuration file at `/etc/elasticsearch/elasticsearch.yml`, should be enough information to create a new VM with a new node. Further, the Azure portal should also have a log of the deployment history for the resource group into which the template was deployed, which should provide the input parameters provided (if they can't be determined from the log files of an existing node).
