### ISSUE TITLE
Apply basic license or remove trial licence from x-pack 5.4

### ISSUE THREAD

**Issue by harshav-dev** [elastic/azure-marketplace#366]
Hi, I have installed elasticsearch 5.4.0 self-managed version, and i have downloaded x-pack 5.4.0 and installed this plugin.
Now after 30 days i am getting not-compliant error and is there any way to get rid of this instead of setting xpack.security: false.
I want to apply basic to the licence, is it possible ? how can i overcome this ?

**Comment by russcam** [comment]
@harshav-dev how did you install Elasticsearch 5.4.0? [5.4.0 went end of life two years ago](https://www.elastic.co/support/eol) so I would recommend deploying a newer version, preferably latest.

With 5.4.0, you need to contact Elastic for a basic license and apply it to the cluster. Please note that for 5.4.0, this is not a perpetual license and there are not security features in the basic license for 5.4.0 to secure the cluster i.e. basic authentication. For this, you'll need [at least 6.8.0 or 7.1.0 with a basic license](https://www.elastic.co/blog/security-for-elasticsearch-is-now-free). The template always deploys with a trial license from the Azure Marketplace, but this can be reverted to a basic license. From the CLI, the template can be deployed with either basic or trial license.
