### ISSUE TITLE
Resizing VMs breaks the cluster?

### ISSUE THREAD

**Issue by janegilring** [elastic/azure-marketplace#369]
In a dev environment we have been running an ELK cluster and a Kibana VM for a while, all using the Standard_D4s_v3 VM SKU.
Today we decided to change the VM size for all of them to Standard_DS2_v2, waiting a few minutes between each VM - hoping the redundancy would handle a reboot which is required for changing VM SKU.

After doing so, both ElasticSearch and Kibana was unavailable.

The Kibana VM show the following status for the kibana service:

```Nov 19 12:49:10 devkibana kibana[4405]:  FATAL  Error: Setup lifecycle of "monitoring" plugin wasn't completed in 30sec. Consider disabling the plugin and re-start.
Nov 19 12:49:12 devkibana systemd[1]: kibana.service: Main process exited, code=exited, status=1/FAILURE
Nov 19 12:49:12 devkibana systemd[1]: kibana.service: Unit entered failed state.
Nov 19 12:49:12 devkibana systemd[1]: kibana.service: Failed with result 'exit-code'.
Nov 19 12:49:15 devkibana systemd[1]: kibana.service: Service hold-off time over, scheduling restart.
Nov 19 12:49:15 devkibana systemd[1]: Stopped Kibana.
Nov 19 12:49:15 devkibana systemd[1]: Started Kibana.
```

And the following for nginx:
```service nginx status
 nginx.service
 Loaded: not-found (Reason: No such file or directory)
 Active: inactive (dead)
```
Is it advised to not resize the VMs? As we know, all temporary disks will be wiped when doing so, could it by accident be stored data on the temp disk?

Didn`t have time and knowledge to troubleshoot any further, so we just destroyed the cluster and created a new one. However, it would be good to know for later why this happened.

**Comment by russcam** [comment]
Hi @janegilring, I would not advise resizing VMs; It's not a scenario that has been tested or supported.

**Comment by janegilring** [comment]
Thanks! Is it possible to spin up a new instance side-by-side and migrate data (indicies) over from the old one? I suppose those are stored in the storage account deployed by the ARM template

**Comment by russcam** [comment]
It should be possible to use [reindex API with reindex from remote](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#reindex-from-remote) to reindex data from one cluster to another, so long as the cluster can reach the other e.g. both attached to the same vnet. 

An alternative that is likely to be quicker would be to [snapshot the data in one cluster to an Azure storage account](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository.html) using the azure repository plugin, and restore the snapshot to another cluster. Note that the format of the data from the source cluster must be compatible with the destination cluster version. If a cluster is deployed using the ARM template in conjunction Azure CLI or PowerShell, [the azure repository plugin can be configured on deployment.](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-plugins.html#azure-repository)

> I suppose those are stored in the storage account deployed by the ARM template

The indices [data is stored on the managed disks attached to each data node, or the temp disk](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-arm-template-data-disks.html) if no managed disks have been attached _(and the warnings have been heeded about using ephemeral storage for persistent data!)_.

**Comment by russcam** [comment]
I'm going to close this issue @janegilring as I think I have answered your questions.

If you have further questions, a great place to ask them is the [discuss forums ](https://discuss.elastic.co/c/elastic-stack/81). There are many more active community members on the forum than view this repository, that are happy to share their knowledge. Another great resource is [the documentation](https://www.elastic.co/guide/en/elastic-stack-deploy/current/index.html).

**Comment by janegilring** [comment]
Sure, forgot to reply to your latest answer. Thanks a lot for the information, very useful!
