### ISSUE TITLE
Problem deploying with self-managed - "Could not update the built-in elastic user" 

### ISSUE THREAD

**Issue by SimonGuldager** [elastic/azure-marketplace#375]
Problem when deploying with template. Version 7.9 

"Could not update the built-in elastic user" 

Details:

3 x master nodes
3 x data nodes
Kibana
2 x logstash

{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'script'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=10\n[stdout]\n[06122020-15:47:01] [apply_security_settings] could not update the built-in elastic user\n\n[stderr]\nsent invalidate(group) request, exiting\nsent invalidate(passwd) request, exiting\nsent invalidate(group) request, exiting\nsent invalidate(group) request, exiting\nsent invalidate(group) request, exiting\nsent invalidate(passwd) request, exiting\nsent invalidate(group) request, exiting\nsent invalidate(passwd) request, exiting\nsent invalidate(group) request, exiting\nsent invalidate(passwd) request, exiting\nsent invalidate(group) request, exiting\nsent invalidate(passwd) request, exiting\nsent invalidate(group) request, exiting\nsent invalidate(passwd) request, exiting\nsent invalidate(group) request, exiting\nsent invalidate(passwd) request, exiting\nsent invalidate(group) request, exiting\nsent invalidate(passwd) request, exiting\nsent invalidate(group) request, exiting\nSynchronizing state of elasticsearch.service with SysV init with /lib/systemd/systemd-sysv-install...\nExecuting /lib/systemd/systemd-sysv-install enable elasticsearch\nCreated symlink from /etc/systemd/system/multi-user.target.wants/elasticsearch.service to /usr/lib/systemd/system/elasticsearch.service.\nrun-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save\nrun-parts: executing /usr/share/netfilter-persistent/plugins.d/25-ip6tables save\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   294  100   265  100    29    613     67 --:--:-- --:--:-- --:--:--   613\r100   294  100   265  100    29    613     67 --:--:-- --:--:-- --:--:--   613\nHTTP 503\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   387  100   387    0     0   1940      0 --:--:-- --:--:-- --:--:--  1944\nHTTP 401\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
}

**Comment by SimonGuldager** [comment]
I see this is adressed #364

**Comment by russcam** [comment]
@SimonGuldager, yes it is
