### ISSUE TITLE
version 6.8.14 can not be installed

### ISSUE THREAD

**Issue by huanghf2018** [elastic/azure-marketplace#380]
try to install in azure portal.
but with error message.

{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'script'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=8\n[stdout]\njinfo (jinfo) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jsadebugd to provide /usr/bin/jsadebugd (jsadebugd) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/native2ascii to provide /usr/bin/native2ascii (native2ascii) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jstat to provide /usr/bin/jstat (jstat) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javadoc to provide /usr/bin/javadoc (javadoc) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javah to provide /usr/bin/javah (javah) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/clhsdb to provide /usr/bin/clhsdb (clhsdb) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jps to provide /usr/bin/jps (jps) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jstack to provide /usr/bin/jstack (jstack) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jrunscript to provide /usr/bin/jrunscript (jrunscript) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javac to provide /usr/bin/javac (javac) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javap to provide /usr/bin/javap (javap) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jar to provide /usr/bin/jar (jar) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/xjc to provide /usr/bin/xjc (xjc) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/hsdb to provide /usr/bin/hsdb (hsdb) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/schemagen to provide /usr/bin/schemagen (schemagen) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/extcheck to provide /usr/bin/extcheck (extcheck) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jarsigner to provide /usr/bin/jarsigner (jarsigner) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jstatd to provide /usr/bin/jstatd (jstatd) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jhat to provide /usr/bin/jhat (jhat) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jdb to provide /usr/bin/jdb (jdb) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/serialver to provide /usr/bin/serialver (serialver) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jfr to provide /usr/bin/jfr (jfr) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/wsgen to provide /usr/bin/wsgen (wsgen) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jcmd to provide /usr/bin/jcmd (jcmd) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jmap to provide /usr/bin/jmap (jmap) in auto mode\r\nSetting up openjdk-8-jdk:amd64 (8u275-b01-0ubuntu1~16.04) ...\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/appletviewer to provide /usr/bin/appletviewer (appletviewer) in auto mode\r\nupdate-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode\r\nProcessing triggers for libc-bin (2.23-0ubuntu11.2) ...\r\nProcessing triggers for ureadahead (0.100.0-19.1) ...\r\nProcessing triggers for systemd (229-4ubuntu21.29) ...\r\nProcessing triggers for ca-certificates (20201027ubuntu0.16.04.1) ...\r\nUpdating certificates in /etc/ssl/certs...\r\n0 added, 0 removed; done.\r\nRunning hooks in /etc/ca-certificates/update.d...\r\n\r\ndone.\r\ndone.\r\n[26012021-08:57:18] [install_java] installed java\n[26012021-08:57:18] [install_es] installing Elasticsearch 6.8.14\n[26012021-08:57:19] [install_es] error downloading Elasticsearch 6.8.14 sha512 checksum\n\n[stderr]\nmke2fs 1.42.13 (17-May-2015)\n\rExtracting templates from packages: 31%\rExtracting templates from packages: 62%\rExtracting templates from packages: 93%\rExtracting templates from packages: 100%\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
}

**Comment by russcam** [comment]
Thanks for opening @huanghf2018. This is a bug that needs to be fixed. In the meantime, you'd be able to deploy any of the 7.x versions from the Azure Marketplace.

**Comment by huanghf2018** [comment]
> Thanks for opening @huanghf2018. This is a bug that needs to be fixed. In the meantime, you'd be able to deploy any of the 7.x versions from the Azure Marketplace.

@russcam Thanks for replying. Would like to know how long azure will keep the 6.x version.

**Comment by russcam** [comment]
Take a look at the End-Of-Life (EOL) support page: https://www.elastic.co/support/eol

In short, 6.8.x will be maintained until 8.0.0 is released. I would recommend using the latest version that you can however, as newer versions will have features that may not be available in 6.x.

**Comment by huanghf2018** [comment]
> Take a look at the End-Of-Life (EOL) support page: https://www.elastic.co/support/eol
> 
> In short, 6.8.x will be maintained until 8.0.0 is released. I would recommend using the latest version that you can however, as newer versions will have features that may not be available in 6.x.

Thanks for replying!

**Comment by russcam** [comment]
Closing this, as it should now be fixed @huanghf2018
