### ISSUE TITLE
Deployment fails due to monit not being restarted 

### ISSUE THREAD

**Issue by ajhewett** [elastic/azure-marketplace#43]
Deployment of a new cluster leads to the following error message:
   `monit: Cannot connect to the monit daemon. Did you start it with http support?`
and the deployment is considered failed.

It looks like the script elasticsearch-ubuntu-install.sh configures monit to monitor the elasticsearch process and only starts, but does not restart, the monit service.  This means that monit does not know about the new configuration and the subsequent call of "sudo monit start all" causes the error message. 

Restarting the monit service and then calling "sudo monit start all" does not produce the error message.

**Comment by Mpdreamz** [comment]
Thanks for reporting this @ajhewett have not seen this in any of the deploys we did prior to getting the update out. 

Are you able to share your arm deployments template variables? privately would be an option too ml-at-elastic.com

(minus the last m (scrapers begone!)).

**Comment by ajhewett** [comment]
The title and description is misleading.  I will open a new issue.
