### ISSUE TITLE
Support for existing Resource Group deployments

### ISSUE THREAD

**Issue by MedAnd** [elastic/azure-marketplace#48]
@russcam Using the new Azure ES deployment template and wondering if there is any way to target an existing resource group? For example I would like to deploy to an existing virtual network within an existing resource group. Thx.

https://portal.azure.com/#create/elastic.elasticsearchelasticsearch

**Comment by russcam** [comment]
@MedAnd yes, with the template version now in the marketplace, you can connect newly deployed resources to an existing virtual network in another resource group in the same location and subscription. 

When using an existing virtual network, deployed resources will **not** be deployed into the existing resource group i.e. VMs, NICs, etc. these will be deployed into the resource group specified in the deployment, but these resources **will** be attached to the existing virtual network.

There are a few details that you need to provide when filling out the template to use an existing virtual network:

<img width="885" alt="screenshot 2016-08-09 16 46 20" src="https://cloud.githubusercontent.com/assets/208231/17507125/3d18a2f2-5e51-11e6-8f57-a081fd58459a.png">

The UI definition will show you the existing virtual networks available in the same subscription and location (as the resource group you're deploying) when deploying. From there, you need to pick the subnet to which to attach the resources; the subnet needs to exist beforehand and have sufficient IP addresses available for the cluster topology you are deploying. For example, for a 3 data node with 3 dedicated master nodes and a Kibana instance, you will need 8 available addresses (3 data, 3 master, 1 Kibana, 1 internal load balancer that Kibana connects to the cluster through).

[We put a blog post out recently detailing some of the new features in the template that may also be useful to go over.](https://www.elastic.co/blog/spinning-up-a-cluster-with-elastics-azure-marketplace-template)

**Comment by MedAnd** [comment]
@russcam So once the deployment completes can the new Resource Group be deleted?

![image](https://cloud.githubusercontent.com/assets/13365135/17507498/3d79c170-5e53-11e6-91cf-a65a78bb6b3b.png)

**Comment by russcam** [comment]
No, the new resource group contains all of the resources deployed as part of the template; **All** of the resources are deployed into the **new** resource group. The difference comes with choosing a new or existing virtual network:

- When choosing a _new_ virtual network, a network resource is also deployed into the **new** resource group
- When choosing an _existing_ virtual network, they are _attached_ to an existing virtual network in another resource group that exists in the same location and subscription.

**Comment by Mpdreamz** [comment]
So until a couple of weeks back you were actually able to deploy into an existing resource group using the marketplace UI. 

The control allowed you to pick an existing resource group and our template has full support for that. For some reason this has been removed, see this issue on the marketplace repos: https://github.com/Azure/azure-marketplace/issues/110

Feel free to make some noise there if you'd like to see that feature back in the UI :smile:

If you use the ARM template directly you might still be able to deploy into an existing resource group, although I have not verified this at the time of writing this.

**Comment by MedAnd** [comment]
@Mpdreamz Will try the ARM .json template and command line to deploy with an existing RG and report back. 

PS. Link to make some noise does not seem to work :-)

**Comment by russcam** [comment]
@MedAnd [+1 and comment on the linked issue to make some noise](https://github.com/Azure/azure-marketplace/issues/110) :bell:

**Comment by MedAnd** [comment]
@Mpdreamz @russcam 

Hi, 

I exported the .json template from the portal today and ran within a PS sessions with New-AzureRmResourceGroupDeployment command, supplying an existing Resource Group, however even though I entered the required passwords the deployment failed with:


New-AzureRmResourceGroupDeployment : 5:05:55 PM - Resource Microsoft.Compute/virtualMachines 'master-0' failed with
message '{
  "error": {
    "code": "InvalidParameter",
    "target": "adminPassword",
    "message": "Required parameter 'adminPassword' is missing (null)."
  }
}'
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -Name AcmeDeployment -ResourceGroupN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Azure
https://github.com/russcamRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet

New-AzureRmResourceGroupDeployment : 5:05:55 PM - Template output evaluation skipped: at least one resource deployment
operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -Name AcmeDeployment -ResourceGroupN

**Comment by MedAnd** [comment]
@Mpdreamz @russcam 

After adding the passwords as default into the template and other small changes such as picking an existing subnet, the deployment succeed! Great work guys, this could not have been simpler... 3 lines and it's all working:

Login-AzureRmAccount
Get-AzureRmSubscription –SubscriptionName "Acme" | Select-AzureRmSubscription
New-AzureRmResourceGroupDeployment -Name AcmeESUATDeployment -ResourceGroupName AcmeUAT -TemplateFile ElasticSearch_UAT_Template.json

**Comment by MedAnd** [comment]
Works using ARM template approach as per above...

**Comment by russcam** [comment]
Awesome, glad you got it working @MedAnd! Are our instructions missing anything that you needed to do but was not detailed?

To clarify, you deployed the resources into an existing resource group?

**Comment by MedAnd** [comment]
So I deployed into an existing Resource Group, VNET and subnet, which also contained an existing external load balancer and a VM scale set with 5 MS Server Fabric VM nodes.

The reason my initial attempt failed seems to be that the passwords had no defaults in the template and even though I was prompted for the passwords and I entered them, the deployment still failed. Not sure if it was me or an issue?

I then added the passwords as default values, in addition to changing the default subnet and also just to be safe changed the internal LB IP (already taken by our external LB).

**Comment by Mpdreamz** [comment]
Thanks for letting us know MedAnd!

The main modus operandi to deploy through ARM templates on the commandline would be as outlined in our README. 

We have not actively tested what happens when you do an export of the template through the portal UI. It will be a concatenated and unrolled version of our template. We should probably add this to our readme.
