### ISSUE TITLE
iptables port forwarding not persist and disappear after reboot

### ISSUE THREAD

**Issue by yaoxiaotong** [elastic/azure-marketplace#49]
The deployment template does a iptables port forwarding from 9201 to 9200 in order to make external load balancer and internal load balancer work together. 

However, I find the the port forwarding disappear after system reboot. and external load balancer stops forwarding traffic. 
I walk around this persist the port forwarding by myself. 

Hopefully the deployment template can persist that in the future.  

I do think the external will be needed for a long while. It hard to put cloud service, app service and Elasticsearch in the same virtual network because of Azure's two different deployment mode.

**Comment by Mpdreamz** [comment]
I do remember testing this so I wonder where I dropped the ball here, we will look into getting this fixed. Thanks for reporting @yaoxiaotong 

We definitely need a walkthrough guide how to connect your cloud/app service tier with our azure arm deployed template, not as clear cut as it oughta be. 

Similarly we are going to blog how to secure your external loadbalancer as well through application gateways. Or even better create one using the template e.g:

https://github.com/Azure/azure-quickstart-templates/tree/master/101-application-gateway-public-ip-ssl-offload

**Comment by russcam** [comment]
Fixed in https://github.com/elastic/azure-marketplace/commit/44b74e41afbf64dd6075976861dd74a63c0e8949 which will be going into the next release, 1.4.0

**Comment by russcam** [comment]
@yaoxiaotong 1.4.0 is now live on the Marketplace.
