### ISSUE TITLE
Elasticsearch restart itself after stop

### ISSUE THREAD

**Issue by yaoxiaotong** [elastic/azure-marketplace#51]
I use command 
"**sodu service elasticsearch stop**" to stop Elasticsearch, however, it restart itself immediately. 
What is the correct way to stop it?

**Comment by russcam** [comment]
[Monit](https://mmonit.com/monit/) is installed onto each VM, to restart the process if it unexpectedly stops. The fact that Elasticsearch is being restarted is a good sign as it indicates monit is working :smile:  To stop the service in a way that monit will not restart it, use

```sh
sudo monit -g elasticsearch stop
```

If you see the error

> monit: Cannot connect to the monit daemon. Did you start it with http support?

Then restart the monit service using

```sh
sudo service monit restart
```

and run the command again to stop the elasticsearch group

```sh
sudo monit -g elasticsearch stop
```

Once you are finished doing what you need to do and have made your changes, you can start elasticsearch service again using

```sh
sudo service elasticsearch start
sudo monit start all
```

This will also start monit again to monitor the elasticsearch service.
