### ISSUE TITLE
Command line deployment fails

### ISSUE THREAD

**Issue by ajhewett** [elastic/azure-marketplace#52]
Create a new cluster using the azure xplat cli, e.g.

    azure group create priv-ajh-es2 westeurope
    azure group deployment create priv-ajh-es2 --template-uri https://raw.githubusercontent.com/elastic/azure-marketplace/master/src/mainTemplate.json --parameters-file "C:\password.parameters.json"

where the contents of `C:\password.parameters.json` is:

    {
      "artifactsBaseUrl":{"value":"https://raw.githubusercontent.com/elastic/azure-marketplace/master/src"},
      "esVersion":{"value":"2.4.0"},
      "esClusterName":{"value":"priv-ajh-es2"},
      "loadBalancerType":{"value":"internal"},
      "kibana":{"value":"No"},
      "jumpbox":{"value":"Yes"},
      "vmHostNamePrefix":{"value":""},
      "vmSizeKibana":{"value":"Standard_D1"},
      "vmSizeDataNodes":{"value":"Standard_DS2"},
      "vmDataNodeCount":{"value":3},
      "dataNodesAreMasterEligible":{"value":"Yes"},
      "vmSizeMasterNodes":{"value":"Standard_DS1"},
      "vmClientNodeCount":{"value":0},
      "vmSizeClientNodes":{"value":"Standard_D1"},
      "adminUsername":{"value":"esadmin"},
      "authenticationType":{"value":"password"},
      "sshPublicKey":{"value":"<value-ignored>"},
      "adminPassword":{"value":"Elastic12"},
      "shieldAdminPassword":{"value":""},
      "shieldReadPassword":{"value":""},
      "shieldKibanaPassword":{"value":""},
      "vNetName": {"value": "priv-ajh-es2-vnet"},
      "vNetSubnetName": {"value": "priv-ajh-es2-subnet"},
      "vNetLoadBalancerIp": {"value": "10.0.0.4"},
      "vNetNewOrExisting": {"value":"new"},
      "vNetExistingResourceGroup": {"value": ""},
      "vNetNewAddressPrefix": {"value": "10.0.0.0/16"},   
      "vNetNewSubnetAddressPrefix": {"value": "10.0.0.0/24"},
      "userCompany": { "value": "" },
      "userEmail": { "value": "" },
      "userFirstName": { "value": "" },	
      "userLastName": { "value": "" },
      "userJobTitle": { "value": "Architect" }
    }

Results in a provisioning failure with an error message ending with:

    ...
    dpkg-preconfigure: unable to re-open stdin: No such file or directory
    monit: Cannot connect to the monit daemon. Did you start it with http support?
    monit: Cannot connect to the monit daemon. Did you start it with http support?
    dpkg-preconfigure: unable to re-open stdin: No such file or directory
    Failed to open terminal.debconf: whiptail output the above errors, giving up!
    dpkg: error processing package iptables-persistent (--configure):
     subprocess installed post-installation script returned error exit status 255
    Errors were encountered while processing:
     iptables-persistent
    E: Sub-process /usr/bin/dpkg returned an error code (1)
    start: Job is already running: walinuxagent

It looks like `iptables-persistent` fails to install silently.

**Comment by Mpdreamz** [comment]
Thanks for raising this @ajhewett not seen this myself.


Can you send us the full `/var/log/arm-install.log` to `microsoft => elastic .co`

Intermittent apt-get problems have lead me to do this for the java install:

https://github.com/elastic/azure-marketplace/blob/master/src/scripts/elasticsearch-ubuntu-install.sh#L228

Maybe that needs to be a function and the general routine for everything we apt-get

cc @elastic/microsoft

**Comment by ajhewett** [comment]
I have sent the full logs by email.

If I ssh into a data node (via jumbbox) and manually run `sudo apt-get -y install iptables-persistent` an interactive UI is displayed to confirm saving of current IPv4 and IPv6 rules.  I had expected that the `-y` option would suppress the dialogue but it does not.

**Comment by ajhewett** [comment]
After recent updates this problem has disappeared.  Possibly the bump to Ubuntu 14.04.4-LTS helped.

For future reference, if this problem should reappear, an interactive dialog can be avoided by setting the DEBIAN_FRONTEND environment variable, e.g.
    `sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install iptables-persistent`

**Comment by Mpdreamz** [comment]
@ajhewett thanks for reporting back on this much appreciated!
