### ISSUE TITLE
Allow more customization of elasticsearch.yml in template config

### ISSUE THREAD

**Issue by cjgeode** [elastic/azure-marketplace#53]
We need to be able to configure more in elasticsearch.yml during template config. Otherwise, you have to ssh to each node and push the file. This could be either validated text fields or a free form box (risky, but most flexible)

**Comment by MedAnd** [comment]
Hi @russcam - this would remove the need for our custom ARM templates... any possible eta?

Thx

**Comment by russcam** [comment]
Hey @MedAnd, apologies for not getting back on this last week, was travelling.

I'm aiming to take a look this week. We need to be a little cautious with this feature as, whilst it provides greater flexibility and additional configuration for the template, it does open up a new avenue for potentially misconfiguring a cluster which could lead to a failed deployments.

**Comment by MedAnd** [comment]
Hi @russcam, no worries... will get your email from Peter... had a few questions around this and some other ideas...

**Comment by russcam** [comment]
@MedAnd Feel free to discuss your questions and ideas here. That way, it provides other users of the template an opportunity to be involved and contribute too 😄

**Comment by MedAnd** [comment]
@russcam some of the other ideas are around container support... so I'll create a new ticket :smiley:
