### ISSUE TITLE
Install Kibana Shield plugin as part of template

### ISSUE THREAD

**Issue by cjgeode** [elastic/azure-marketplace#55]
Today, when the template installs, we do not install the Kibana Shield plugin. Mostly, this is ok, however, the following problems are present:

1. Graph UI does not work. When you click on the search button, you get an "Unauthorized Operation" at the top, and no apparent errors in any logs.

2. No logout button is available in Kibana. You have to brute force switching users.

I recall a conversation about choosing not to do this because we were going to need to set up SSL. We could either set up SSL, or possibly allow a flag in the config to not require SSL for the plugin.

I would make this a pretty high priority. We want our marketplace offering to match our product offering. Could we model what we do in cloud?

**Comment by russcam** [comment]
I've just pushed a commit that installs Shield in Kibana for Elasticsearch versions greater than 2.4.0.

In order for shield to work, two settings need to be set in `kibana.yml`

```
shield.useUnsafeSessions: true
shield.skipSslCheck: true
```

this allows shield with Kibana to bypass checking that it's running over HTTPS and also allow it to send the session/authentication cookie over HTTP. [I have added a note to the README](https://github.com/elastic/azure-marketplace#very-important) to highlight that these should be removed  and transport layer security is strongly recommended before going into production.
