### ISSUE TITLE
Invalid ES_HEAP_SIZE setting prevents elasticsearch starting

### ISSUE THREAD

**Issue by batwad** [elastic/azure-marketplace#62]
I'm guessing that the template looks at the VM size and sets the `ES_HEAP_SIZE` value in `/etc/default/elasticsearch` to half the VM's memory, as per the usual recommendations.  In a deployment I've just done to a cluster of small nodes with 3.5GB memory and had the following setting:

`ES_HEAP_SIZE=1719.5m`

elasticsearch wouldn't start and there were no errors or logs reported, but by removing `.5` from the setting I was able to get the service running.  Looks like the value needs to be an integer.

**Comment by Mpdreamz** [comment]
Hi @batwad 

Deploying through the template and from the `master` branch of this repos directly i end up with:
```
ES_HEAP_SIZE=1720m
```

In all cases. 

Can you share a bit more about your VMsize/elasticsearch version/parameters.

**Comment by batwad** [comment]
I'm not sure what details exactly you need, and how to get them.  It's a corporate deployment so I'm reluctant to dump everything.

I should confess to editing the template: my client wanted to deploy to a UK data centre and when I tried to do this I got a validation error rejecting UK South (I exchanged emails with @russcam about this) so I downloaded the template from the marketplace, added the locations and deployed that.

**Comment by russcam** [comment]
@batwad I experienced this when deploying an Elasticsearch 5.x cluster to Ubuntu 16.04-LTS; I've added a fix for it in #90 👍

**Comment by russcam** [comment]
This is now merged into `master` if you would like to try again, @batwad. 

Closing this, but feel free to reopen if you still experience the issue.
