### ISSUE TITLE
Install support diagnostics by default on all nodes

### ISSUE THREAD

**Issue by cjgeode** [elastic/azure-marketplace#63]
For easier debugging, install support diagnostics on all nodes deployed as part of Azure template.

Need to validate that diagnostics are accurate at OS and hardware level.

**Comment by niemyjski** [comment]
What do you mean by diagnostics? @cjgeode

**Comment by russcam** [comment]
It's referring to the Diagnostic tooling that Elastic support uses to evaluate the state of the cluster.

I had a conversation with @joshuar about this and came to the conclusion that this is something we shouldn't do by default; the tooling can be updated and change over time with versions. I think it would be better to install the tooling when needed to diagnose issues.

Closing this issue.
