### ISSUE TITLE
Configure Application Gateway instead of External Load Balancer

### ISSUE THREAD

**Issue by russcam** [elastic/azure-marketplace#66]
Application Gateways are able to be configured for SSL termination, allowing for transport level security to be configured at deployment time.

The template should create an Application Gateway instead of an External Load Balancer, and allow the user to specify a certificate (pfx) for HTTPS.

**Comment by yaoxiaotong** [comment]
Is external load balancer still an option? If not can I add load balancer by myself? I am acctually happily using  load balancer and using network security rule to secure elasticsearch vms.

**Comment by russcam** [comment]
@yaoxiaotong The external load balancer would still be an option, yes.
