### ISSUE TITLE
Add a way to control the storage size.

### ISSUE THREAD

**Issue by gkorland** [elastic/azure-marketplace#69]
The current template deploys 2 1TB premium storage per instance. 
Is there a way to add some control to the template of the disk size?

**Comment by niemyjski** [comment]
This is being worked on in a branch currently

**Comment by russcam** [comment]
This has now been merged into `master` in 10e02c16a1464d874fb8f8b5346fc73d83555a64.

The ARM template exposes a way to configure:

- Number of disks attached to each VM (up to supported number on VM size)
- Size of disks attached; 128Gb, 512Gb, 1024Gb
- Whether disks use Standard or Premium Storage (if the VM size support Premium Storage).

Check out the README for more details 👍
