### ISSUE TITLE
Cluster not working as expected after license expire

### ISSUE THREAD

**Issue by gkorland** [elastic/azure-marketplace#70]
After license expire as defined in [License Management](https://www.elastic.co/guide/en/x-pack/current/license-management.html) the cluster should operate without stat API.

But, it seems like the all cluster is not working once the license expire.

**Comment by niemyjski** [comment]
@gkorland did you find a solution to this?

**Comment by gkorland** [comment]
No

**Comment by russcam** [comment]
@gkorland could you provide more detail around what does and doesn't work after license expire e.g. can you still ping the cluster? Can Kibana (if installed), access the cluster?

**Comment by russcam** [comment]
Closing as no additional feedback given.

Feel free to reopen if you have more detail @gkorland 👍

**Comment by gkorland** [comment]
Sorry I missed your question from January, 
"Can Kibana (if installed), access the cluster?" No.
"can you still ping the cluster?" Yes, but it seems like the cluster is not being able to recover the shards and decide on a primary.

Anyway, thanks for the update, we're no longer using the this template so I won't have any more feedback.
