### ISSUE TITLE
Kibana is not installed as a service

### ISSUE THREAD

**Issue by gkorland** [elastic/azure-marketplace#72]
On Kibana machine restart the Kibana service doesn't restart

**Comment by leibale** [comment]
It's not working only from ubuntu 15.04 because ubuntu switched from `upstart` to `systemd`

**Comment by Mpdreamz** [comment]
Thank you for reporting this @gkorland.

I just added support for Elasticsearch & Kibana 5.x and moved the kibana installation over to using the debian package. 

https://github.com/elastic/azure-marketplace/pull/75

This will also properly install the service (upstart or systemd depending on system). 

So starting with 5.x this should no longer be an issue.
