### ISSUE TITLE
Upgrade images to Ubuntu Server 16.04.1 LTS

### ISSUE THREAD

**Issue by niemyjski** [elastic/azure-marketplace#80]
Is there any reason for running 14LTS?

**Comment by russcam** [comment]
Yes, [Elasticsearch 2.x is not supported on it](https://www.elastic.co/support/matrix); only Elasticsearch 5.0+ is.

**Comment by niemyjski** [comment]
I'm running 15.x and 16.x on our 1.7.6 cluster/dev nodes with no issues. You could special case it as you know which version of ES is being installed and I'd argue that you should remove creating 1.x and 2.x clusters from this script and only support the latest version (They can go back to older versions of the arm script via a tag).

**Comment by niemyjski** [comment]
I wonder why alpine isn't listed in that matrix.

**Comment by niemyjski** [comment]
@russcam I'd really hate to start off on a version of an OS that I know is already 1-2 years into it's LTS and that now I have a cluster where I need to preform a major rolling restart and update each os which could fail. I can help test this and ensure everything works.

**Comment by russcam** [comment]
I've added PR #90 to use Ubuntu 16.04 LTS when deploying an Elasticsearch 5.x cluster.

**Comment by niemyjski** [comment]
Is this the only change that's required?

**Comment by russcam** [comment]
From my tests, yes
