### ISSUE TITLE
mlockall is off by default..

### ISSUE THREAD

**Issue by niemyjski** [elastic/azure-marketplace#94]
I've verified that it's off by default https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall

**Comment by niemyjski** [comment]
This made a massive difference for us.

**Comment by russcam** [comment]
what does `sudo cat /proc/swaps` return on the data nodes? If I run this, I get

```
russ@data-0:~$ sudo cat /proc/swaps
Filename                                Type            Size    Used    Priority
```

which means that swap is not enabled on the VM. From what I can see and find, swap is not enabled by default on Linux VMs in Azure.

I don't _think_ there's any harm in setting it in configuration as part of the deployment, though; what difference did it make for you, @niemyjski?

**Comment by niemyjski** [comment]
We were seeing barely any ram being consumed and all time view over daily indexes was painfully slow and thrashed the disks, it was like it was being evicted after a few seconds. We checked the setting in Kibana as well as the handle limit. We noticed it was off. After turning it on it made a massive difference in terms of long term perc when indexes we're warm, also seemed faster on cold start too. We both were shocked and wondered what else might we be missing

**Comment by niemyjski** [comment]
I'll check that tomorrow

**Comment by russcam** [comment]
[Commented this out again](https://github.com/elastic/azure-marketplace/commit/ebe134c51bf53fc5596eaeef3327670dc0b784a2) within the template because the JRE fails to launch with insufficient memory and the following error:

    Native memory allocation (mmap) failed to map 1716322304 bytes for committing reserved memory.

Need to investigate further. Memory lock shouldn't make any difference on Azure Linux VMs however as swap is disabled by default.

**Comment by niemyjski** [comment]
It does matter, we seen tons of perf issues with it disabled

**Comment by niemyjski** [comment]
Thanks!
