### ISSUE TITLE
Additional installed plugins are not marked as mandatory plugins.

### ISSUE THREAD

**Issue by niemyjski** [elastic/azure-marketplace#96]
I noticed that the additional plugins I had installed, were not in the elastic config as mandatory plugins.

Also, It might be nice if we had a commented out auto_create_index list for xpack :)

**Comment by russcam** [comment]
> I noticed that the additional plugins I had installed, were not in the elastic config as mandatory plugins.

I'm not sure what you mean; could you elaborate?

**Comment by niemyjski** [comment]
Thanks!
