### ISSUE TITLE
Add documentation for the ARM template to Elastic.co

### ISSUE THREAD

**Issue by russcam** [elastic/azure-marketplace#97]
Add a section to the [documentation on elastic.co](https://www.elastic.co/guide/index.html) for working with the ARM template.

@clintongormley, where would be a good fit for such documentation? Under **Elasticsearch: Store, Search, and Analyze**?

**Comment by clintongormley** [comment]
@russcam it definitely shouldn't be a top-level item in the docs ToC.  I'm guessing this is mostly about installation and setup? in which case I'd add it to the ES docs under installation: https://www.elastic.co/guide/en/elasticsearch/reference/current/install-elasticsearch.html

**Comment by russcam** [comment]
There are a few different topics to document:

### Marketplace UI

An overview of what the simplified Marketplace UI offers

### ARM Template

General documentation on:

#### Deploying bigger clusters

- Subscription Core quota limits
- Availability Sets, Update and Fault Domains
- Internal Load Balancer setup when deploying client nodes
- Incremental scale up (and down).

#### Data Disk Configurations

- Standard and Premium Storage
- RAID 0 and Temporary disks
- Sizes

#### Networking

- Deploying to new or existing virtual network.
- Application Gateway and SSL Offload

#### Extending

- Installing additional plugins
- Azure cloud plugin for snapshot/restore

#### Troubleshooting

- Accessing nodes in the cluster
- Diagnosing issues through installation logs
- Repeated deployments of specific template versions
- Advanced scenarios
  - More than one cluster in one Virtual Network
  - Configuring App Services to connect to the cluster on a private network

The template can deploy both an Elasticsearch cluster and Kibana; would a section under [Installing the Elastic Stack](https://www.elastic.co/guide/en/elastic-stack/current/installing-elastic-stack.html) be appropriate?

**Comment by clintongormley** [comment]
> The template can deploy both an Elasticsearch cluster and Kibana; would a section under Installing the Elastic Stack be appropriate?

Hmm maybe, or split it over the ES and Kibana docs.  @eskibars what do you think?

**Comment by eskibars** [comment]
This is tricky.  I'm +1 to splitting, but also to having a stub in the stack docs to link to the individual components as we already.  Putting it (just) in the stack docks is going to provide less visibility right now.  While the template can deploy both Kibana+Elasticsearch, we have reserved sections for installing either individually and leaving this (just) in the stack docks I feel is going to result in people missing how to use this.  We could include in the docs that it can be used to deploy Kibana as well and then put a brief note just under the `Installation Order` about the ARM template then and link to the docs here.  WDYT?

**Comment by djcecil** [comment]
@russcam @lawrenceau1 this is now ready to stage. 

Here is the net new copy for the Azure Marketplace partner page ([Google Doc](https://docs.google.com/document/d/1sL3M5vOmge1et0aK_MdcNgw5VVivtCJApATvE-7eOzA/edit))

Here is the Overview Page ([Google Doc](https://docs.google.com/document/d/1LO14rtl64Sazva6-5j01M_MGac4vvN6OE9TIs4EEB_U/edit)). FYI: For now, only apply the changes made in the [second paragraph](https://docs.google.com/document/d/1LO14rtl64Sazva6-5j01M_MGac4vvN6OE9TIs4EEB_U/edit#bookmark=id.yxelha4zo9a0) of the Microsoft section of the Overview. All other suggestions in the doc are for potential changes to the page in the future.

**Comment by hstephenson** [comment]
@djcecil just realized where this update was. We should actually put this update as a new ticket in the website repo here: https://github.com/elastic/website-www.elastic.co/issues. (This repo is handling other work. =) )

Feel free to connect with me or Liz on Monday and we can help out.

**Comment by russcam** [comment]
Thanks @djcecil / @hstephenson, this issue is to track adding technical reference documentation for the template to the elastic website so not the one you're looking for for the Partner page 😄
