### ISSUE TITLE
Trouble running npm run build

### ISSUE THREAD

**Issue by nickelbob** [elastic/azure-marketplace#99]
When I do 'npm run build' I get 

C:\Users\bla\Development\azure-marketplace (master) (elasticsearch-arm-template@0.0.0)
λ npm run build

 elasticsearch-arm-template@0.0.0 build C:\Users\bla\Development\azure-marketplace
 gulp --gulpfile build/gulpfile.js

[16:22:46] Working directory changed to ~\Development\azure-marketplace\build
module.js:471
    throw err;
    ^

Error: Cannot find module '../.test.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\bla\Development\azure-marketplace\build\tasks\arm-test-deploy.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! elasticsearch-arm-template@0.0.0 build: `gulp --gulpfile build/gulpfile.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elasticsearch-arm-template@0.0.0 build script 'gulp --gulpfile build/gulpfile.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elasticsearch-arm-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --gulpfile build/gulpfile.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs elasticsearch-arm-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls elasticsearch-arm-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bla\Development\azure-marketplace\npm-debug.log

I tried using .test.example.json as well but that failed because it has no values in it. Do I have to include all those values just to build the template? If so, why isn't there any guidance on this part in the readme?

Thanks!

**Comment by russcam** [comment]
`.test.example.com` is included as an example of the properties you need to include in `.test.json`. [Take a look at the guidance](https://github.com/elastic/azure-marketplace/blob/master/build/README.md) which runs through how to build the solution, develop and test. Renaming `.test.example.json` to `.test.json` is enough to build the solution, but you would need to set up a service principal as per the guidance and fill in the values in order to run the test task.

Hope that helps 👍

**Comment by nickelbob** [comment]
Sorry, I'm still stuck. In the guidance it says:

1). Run the following to bring down all the dependencies
$ npm install
2). To build the project call
$ npm run build

npm run build fails for me b/c there's no .test.json. I'm not particularly interested in running the test, is there a way to build the project without testing it?

**Comment by annegi** [comment]
Has this been answered anywhere?..Because I am stuck with the same issue

**Comment by russcam** [comment]
`.test.json` is a required file for the gulp tasks, even if you're not running a task that uses it.

The easiest way to solve this is to copy `.test.example.json` and rename the copy to `.test.json`

**Comment by annegi** [comment]
got it..thanks !!

**Comment by pijemcolu** [comment]
This is still an issue. It should be either documented or fixed.

```
npm i
cp ./build/.test.example.json ./build/.test.json
npm run build
```
/build/.test.json is ignored in .gitignore, it could also just be forced into the repo.
